### ISSUE TITLE
rocksdb snapshot doesn't released and make space not reclaimed.

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#10027]
### What version of TiKV are you using?

v4.0.11

### What operating system and CPU are you using?

not related

### Steps to reproduce

Can't reproduce

### What did you expect?
space is properly reclaimed

### What did happened?

![image](https://user-images.githubusercontent.com/13497871/114964885-2f46ed00-9ea2-11eb-9c1c-ade04118347e.png)
rocksdb snapshot is held about 1.2 weeks, which causes region worker won't clean up the data of region when the peer is removed.

![image](https://user-images.githubusercontent.com/13497871/114964934-3ff76300-9ea2-11eb-8a2a-68967cbcf618.png)
there are 8 rocksdb snapshots leaked. And it happens in multiple tikv nodes. There must be something wrong that the rocksdb snapshot release is not properly called or some threads got stuck.

**Comment by zhangjinpeng1987** [comment]
Do they use TiCDC?

**Comment by Connor1996** [comment]
> Do they use TiCDC?

Not sure, but they use BR

**Comment by Connor1996** [comment]
> Do they use TiCDC?

Confirmed, they don't use TiCDC

**Comment by Connor1996** [comment]
It's because TiKV is blocked on uploading SST to S3 for a long time due to external issues (maybe S3 client, maybe nginx). So the snapshot can't be released until the upload is finished.

**Comment by mzygQAQ** [comment]
@Connor1996 @zhangjinpeng87 I also meet this issues in our tikv clusters.  the oldest snapshot duration in our cluster reach that 2days, this leads to a sharp rise in our disk usage (due to the high-frequency updates in our biz scenario). 
we never use BR  and CDC。

It's difficult to investigate the root cause online, so I conducted some analysis based on TiKV's code—though I'm not sure if it's accurate.

I found that the LocalReader caches a snapshot, which is reused when the ReadID is the same (likely in BatchGet/RawBatchGet scenarios). Both LocalReader and Engine are cloned and ws stored in Thread Local storage, meaning each thread in the ReadPool and Scheduler Pool holds its own copy.

If a read or write thread in the  read pool or scheduler pool stops accepting new requests at some time point (such as idle), this cached snapshot will be retained indefinitely—unless TiKV is restarted.
