### ISSUE TITLE
*:Logger thread can be bottleneck and slow down the whole TiKV instance

### ISSUE THREAD

**Issue by sunxiaoguang** [tikv/tikv#10841]
### What version of TiKV are you using?

4.0.14

### What operating system and CPU are you using?

Linux x86_64

### Steps to reproduce

Send extreme coprocessor load to a single region to trigger enormous  amount of slow log that can overload slogger thread. Once slogger thread is overloaded, log message can accumulate and fill up pending message queue quickly. All code path that generates log are affected and can't make progress as usual.   

### What did you expect?
Try to send less slow log to slogger at first to make it less likely to collapse. And having a mechanism to short circuit not critical logs when slogger thread is heavy loaded.      

### What did happened?
Slogger thread uses 100% CPU and slow down everything. Especially coprocessor.

**Comment by BusyJay** [comment]
I propose to reduce the slow log count and enlarge the log buffer to twice the current. Also @sticnarf suggested to replace mpsc channel in slog-async as crossbeam channel, which should be faster.

**Comment by zhangjinpeng1987** [comment]
The bottleneck is the formatting part of slogger, I prefer
1) using OverflowStrategy::Drop instead of OverflowStrategy::Block for short term solution, since print log become the bottleneck is not a frequently thing. So the first priority is keep the service is OK under any throughput.
2) simplify and reduce the total number of log when the throughput is high, we need to sample the same type logs to guarantee key messages are logged. Also I prefer using OverflowStrategy::Drop when the slogger is overflow.

**Comment by sticnarf** [comment]
## Short-term solution

I agree to reduce the slow log count first by changing the `req_lifetime` to `total_process_time`: https://github.com/tikv/tikv/blob/19e4d00ad7965681b5139cd71c7eaf8290cc22ce/src/coprocessor/tracker.rs#L249 

And not all errors need to be logged here https://github.com/tikv/tikv/blob/19e4d00ad7965681b5139cd71c7eaf8290cc22ce/src/coprocessor/endpoint.rs#L635

I'm afraid it is not useful to enlarge the log buffer. If the bottleneck is the slogger thread, however large the buffer is, the buffer will be finally filled full.

## Mid-term solution

We fork slog project and add `try_log` macros which allows dropping the log when the buffer is full. I think the feature is useful for other users and may be potentially accepted by the upstream.

**Comment by sunxiaoguang** [comment]
> I'm afraid it is not useful to enlarge the log buffer. If the bottleneck is the slogger thread, however large the buffer is, the buffer will be finally filled full.

As long as log gets accumulated, it's just a matter of time before queue gets filled up. One workaround can be using a large enough slow log threshold to effectively disable coprocessor slow log. With the not critical warning log filtered, I think it's quite safe for now.

**Comment by breeswish** [comment]
My ideas are separated as short-terms and long-terms, where short-terms are easy to implement, can be effectively backported, while long-terms are more advanced with the complexity cost:

1. Change `req_lifetime` to `total_process_time`. It is almost always a good change, which reduces direct cause of logging channel full.

2. Short-term: Just drop logs. Worth to output "xxx logs dropped due to reaching xxx limit".

3. Long-term: More fine-gained control, e.g. limit the rate and drop logs by modules, to avoid missing some other important logs.

4. Long-term: Collapse similar logs at the output site.

**Comment by sunxiaoguang** [comment]
> I'm afraid it is not useful to enlarge the log buffer. If the bottleneck is the slogger thread, however large the buffer is, the buffer will be finally filled full.

As long as log gets accumulated, it's just a matter of time before queue gets filled up. One workaround can be using a large enough slow log threshold to effectively disable coprocessor slow log. With the not critical warning log filtered, I think it's quite safe for now.
