### ISSUE TITLE
Require integration-copr-test for PRs

### ISSUE THREAD

**Issue by tisonkun** [tikv/tikv#10877]
Previous discussion at https://github.com/tikv/tikv/issues/10850#issuecomment-907790421

cc @skyzh @breeswish @zhouqiang-cl @purelind

**Comment by skyzh** [comment]
Indeed, I don't understand why we postpone the integration test check to the master branch. If developers break the integration test and go back to fix this, the number of integration test runs are not reduced...

**Comment by skyzh** [comment]
Anyway, we could always manually run the integration test. But if anyone else breaks the test, when waiting for the fix, no one could confidently merge any new PRs into master.

**Comment by XuHuaiyu** [comment]
The reason why we postpone the integration-test check to the master branch was mentioned [here](https://github.com/tikv/tikv/issues/10850#issuecomment-908031811). @skyzh

**Comment by skyzh** [comment]
> The reason why we postpone the integration-test check to the master branch was mentioned [here](https://github.com/tikv/tikv/issues/10850#issuecomment-908031811). @skyzh

> We assumed some one will watch master's status and fix potential problems. Though it seems to be contrary.

And the fact is that integration test has been broken for nearly a week 😂

**Comment by tisonkun** [comment]
@skyzh @XuHuaiyu I'm curious whether copr test is integration test. Or say, what's the cost it brings?

I think we previously move all tests match "integration-test-*" to master CI, but compatibility tests can be more lightweight? 

Also there is an undergoing trending to running tests based on file changes, but it may be a long-term effort.

**Comment by tisonkun** [comment]
@skyzh @XuHuaiyu I think the fail root of master ci has nothing to do with copr cases. Let's focus on this topic "Require integration-copr-test for PRs".

**Comment by skyzh** [comment]
> I'm curious whether copr test is integration test. Or say, what's the cost it brings?

When someone changes the SQL expression implementation on the TiKV side, we need to ensure it has the same output as TiDB. This is copr-test. On the other way, when we are doing some memory layout optimizations, it is possible that TiDB cannot successfully decode the chunk data, and this encode-decode thing is not covered by TiKV unit tests. This could be covered with integration-test. Therefore, it's better to run those tests before PRs are merged.

I agree that we could manually trigger it, but I still believe that, if integration test is a requirement for merging (especially for those PRs involving copr changes), we should let the bot determine whether a PR could be accepted instead of letting reviewers manually trigger the tests.

**Comment by tisonkun** [comment]
Closed as no more activities.
