### ISSUE TITLE
Correct test coverage information in README

### ISSUE THREAD

**Issue by tisonkun** [tikv/tikv#10949]
It is currently reported as 10%. According to @sticnarf , it is not true. We'd better try to replace it with real metric.

**Comment by sticnarf** [comment]
Rust supports source-based code coverage provided by LLVM. Here is the guide: https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/instrument-coverage.html

Raw profiles can be generated using:

```bash
$ export RUSTFLAGS="-Z instrument-coverage"
$ export LLVM_PROFILE_FILE="tikv-%m.profraw"
$ make test # Due to flaky tests, we can disable failfast and kill timeout tests here
```

Merge all generated raw profiles into one:

```bash
$ find -name '*.profraw' | xargs llvm-profdata --merge -sparse -o tikv.profdata
```

Using `llvm-cov` to generate report:

```
$ cargo cov -- report \
    --ignore-filename-regex='/.cargo/registry' \
    --ignore-filename-regex='/.cargo/git/checkouts' \
    --instr-profile=tikv.profdata \
    --object .. \
    --object .. \
    --object ..
```

The object list can be generated using `find ./target/debug/deps -executable -type f ! -name '*.*'`.

This is the way of generating line coverage. I am not familar with the integration of platforms like codecov.

**Comment by tisonkun** [comment]
@sticnarf @Ray-Eldath I think the problems here are:

1. Find a way to calculate real test coverage.
2. Display on README.md.

@sticnarf 's script above can resolve the first part, what about the second part? Where we can send the report and generate a result (daily? per check-in?) to display.

If it is hard to achieve, we may just remove the current status first.

**Comment by hi-rustin** [comment]
I think I can explain why the coverage plummets.
1. first codecov works on the principle that it needs a base branch as a benchmark, then PR runs the test and then compares the diff to determine the coverage change.
2. The reason for our plunge is that https://codecov.io/gh/tikv/tikv/commit/d05d8ae3fe0bc81901550c554de4f37dd4f6cc26/ is a failed statistic, you observe that it doesn't actually find the result on the corresponding master, so the comparison fails and only produces PR coverage.
![image](https://user-images.githubusercontent.com/29879298/133451764-9c319320-d26d-4409-9f12-4889f5a71a70.png)

3. Since we don't consistently run tests to count coverage after the PR is merged to master, it hasn't been able to count coverage to master correctly. Looking at codecov our last tally on master was 4 months ago.


So I think we can solve the problem by running the test upload results correctly on master.

**Comment by BusyJay** [comment]
Now the coverage information is displayed correctly. A daily run task will be setup once https://github.com/PingCAP-QE/ci/pull/608 is merged.

**Comment by BusyJay** [comment]
Daily run task is setup. Close.
