### ISSUE TITLE
Adopt new DCO validator

### ISSUE THREAD

**Issue by tisonkun** [tikv/tikv#11078]
According to https://github.com/probot/dco/issues/162, DCO App is possibly offline in weeks.

Even if there is new maintainer volunteering, it can be considered to adopt new stable DCO validator.

**Comment by hi-rustin** [comment]
Maybe we can use the tichi DCO plugin. You can checkout  https://prow.tidb.io/plugins or https://prow.tidb.io/command-help#check_dco.

But it should not work for projects that do not use tichi.

My other proposal is to deploy dco ourselves, we have proven experience using and deploying probot. Many of our bots are also built using probot. cc: @Mini256

Regarding @tisonkun 's proposal, I'm worried about the GitHub actions quota, since the whole org is going to use GitHub actions. also for some projects this will introduce new test platforms (like tikv).
