### ISSUE TITLE
After a tikv failure is recovered, the leader of this tikv is always zero

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#11075]
### What version of TiKV are you using?
/ # ./tikv-server -V
TiKV 
Release Version:   5.0.1
Edition:           Community
Git Commit Hash:   e26389a278116b2f61addfa9f15ca25ecf38bc80
Git Commit Branch: heads/refs/tags/v5.0.1
UTC Build Time:    2021-04-23 08:24:13
Rust Version:      rustc 1.51.0-nightly (bc39d4d9c 2021-01-15)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?
                 cpu: 8000m
                 memory: 16Gi

### Steps to reproduce
Simulate a tikv down（1 min）, network packet loss（1 min） and delay（1 min） respectively

### What did you expect?
After failure recovery，the leader is balanced

### What did happened?
After a tikv failure is recovered, the leader of this tikv is always zero
![image](https://user-images.githubusercontent.com/84712107/137505814-1acd1780-dc07-4ef8-9395-e085eb961b33.png)

**Comment by Connor1996** [comment]
From the log, we can see one region is always rejecting the request vote from tikv-1
![image](https://user-images.githubusercontent.com/13497871/137570315-a04f7727-781d-4cea-be4d-4ab8b4ba93dd.png)

It's due to tikv-0 and tikv-2 is unreachable to tikv-1
![image](https://user-images.githubusercontent.com/13497871/137570924-6ea95d05-2be3-4026-95db-56a753fa9e11.png)

The unreachable state comes from the connection abort caused by large grpc msg 
![image](https://user-images.githubusercontent.com/13497871/137570952-da7cb240-f87d-47e2-90ac-3301e0c173f9.png)
![image](https://user-images.githubusercontent.com/13497871/137571220-c3cf4828-1a08-4a51-a413-d0c0e237cb79.png)

**Comment by Little-Wallace** [comment]
Is this problem same to https://github.com/tikv/tikv/issues/9714 ?

**Comment by Little-Wallace** [comment]
I think https://github.com/tikv/tikv/pull/11493 has solved this problem
