### ISSUE TITLE
Flaky test raftstore::test_unsafe_recover::test_unsafe_recover_update_region 

### ISSUE THREAD

**Issue by v01dstar** [tikv/tikv#11262]
## Bug Report

The test_unsafe_recover_update_region in the file "tests/integrations/raftstore/test_unsafe_recover.rs" some times panics, saying "region update for unsafe recover should only occur in leaderless region".

**Comment by BusyJay** [comment]
It fails again. Seems not a problem with timeout. The logs and stacktrace can be found at https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/10914/nodes/112/steps/271/log/?start=0.

```
region 1's replica in store 1 still has a valid leader after 5 secs
```

**Comment by BusyJay** [comment]
It fails again. See https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/12977/pipeline/113. The reason why it fails is because the leader is hibernated after a round of ping. If all followers have caught up logs, and there are no pending requests, the leader will still go to sleep even all followers are unavailable.

**Comment by BusyJay** [comment]
You should use a read request to guarantee leadership instead of just querying the leader role.
