### ISSUE TITLE
Reverse scan can't detect memory locks

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#11440]
## Bug Report

`Storage::scan()` always uses range [start_key, end_key) to check memory locks

https://github.com/tikv/tikv/blob/0b3655275712b0dd04de5fd83cddc408034f4b8b/src/storage/mod.rs#L843

but reverse scan's start_key is greater than end_key
https://github.com/pingcap/kvproto/blob/03abd340988f539630450c78ead7b13dcf5e056d/proto/kvrpcpb.proto#L56-L58. It results in that reverse scan can't detect memory locks and may read old data.

**Comment by sticnarf** [comment]
For TiDB, the only use of reverse kv_scan is https://github.com/pingcap/tidb/blob/d15ca2a869b95a03d80c780400af211ff6940aa5/ddl/backfilling.go#L456

Not being blocked by the memory lock will not the correctness of backfilling because DDL reorg happens after all async commit txns with previous schema commit successfully.

TiSpark does not use reverse scan.

Other client-go users may be affected but I don't know their use cases.
