### ISSUE TITLE
bkwkr paniced in test_adjust_thread_pool_size 

### ISSUE THREAD

**Issue by 3pointer** [tikv/tikv#11548]
## Bug Report

run `make dev` and found
```
thread 'bkwkr' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /data4/juncen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/shutdown.rs:51:21
```
### What version of TiKV are you using?
master

### Steps to reproduce

run `make dev` on master

### What did you expect?
do not panic bkwkr
### What did happened?
bkwkr paniced though test passed🤔

**Comment by YuJuncen** [comment]
This panic can be reproduced via those steps:
```rust
let mut pool = ControlThreadPool::new();
pool.adjust_with(1);
pool.spawn(async { tokio::time::sleep(Duration::from_millis(100)).await });
pool.adjust_with(2);
drop(pool);
```
The reason is that we force all spawned futures hold the reference to the thread pool:
```rust
fn spawn<F>(&self, func: F)
    where
        F: Future<Output = ()> + Send + 'static,
    {
        let workers = self.workers.as_ref().unwrap();
        let w = workers.clone();
        workers.spawn(async move {
            func.await;
            // Debug service requires jobs in the old thread pool continue to run even after
            // the pool is recreated. So the pool needs to be ref counted and dropped after
            // task has finished.
            drop(w);
        });
    }
```
When any spawned task wants to drop the runtime, tokio would complain that we are trying to block the current thread (even it is the last task and won't block at all🤷‍♂️).

The simplest way to fix this is don't let the task to drop the runtime, but call `workers.shutdown_background()` in `adjust_with()`, but I'm not sure how this impacts the debug service, cc @NingLin-P.

**Comment by YuJuncen** [comment]
BTW, this panic is probably harmless: after the panic, the runtime get dropped properly(hopefully...), and the test get passed...
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/36239017/144539369-e53b3da9-a1aa-4619-8b45-cfde07af5e87.png">
