### ISSUE TITLE
GcKeys tasks in GC worker block UnsafeDestroyRange requests and make GC stuck

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#11752]
### What version of TiKV are you using?

/ # /tikv-server -V
TiKV
Release Version:   5.4.0-alpha
Edition:           Community
Git Commit Hash:   28bf633141e05fa9ce1e04444bc7865da258ef02
Git Commit Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time:    2021-12-30 00:11:41
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### Steps to reproduce

oltp_rel_008, drop one database, inject tikv instance down some times, after tikv recover, check the gc safepoint.

### What did you expect?
gc safepoint should push ahead after recover from tikv failure.

### What did happened?
![image](https://user-images.githubusercontent.com/9443637/147719955-aa51057c-7ece-4c7d-b508-6e33f200d780.png)

**Comment by mayjiang0203** [comment]
Logs can be get from minio via testbed-oltp-hm-67jfl.

**Comment by MyonKeminta** [comment]
![origin_img_v2_80e091b1-6684-4b42-99ef-dab6cb056feg](https://user-images.githubusercontent.com/9948422/147721285-4548fbdb-b499-4498-9325-df976a2efbd8.png)

In this case the `GcKeys` tasks in GC worker are relatively slow. There seems to be queueing tasks in GC worker so that `UnsafeDestroyRange` requests takes minutes in gRPC duration.

We may consider:
1. Optimize `GcKeys` tasks
2. Make `UnsafeDestroyRange` executes with higher priority to avoid being blocked by `GcKeys` for too long (but in the other way `GcKeys` might be blocked by `UnsafeDestroyRange`).

cc @hicqu

**Comment by mayjiang0203** [comment]
Also hit it when try to drop 1T data, there are about 10 database, one database has 100 tables, one table has 5000,000 rows, gc stuck for more than 1 hours .

**Comment by mayjiang0203** [comment]
![Uploading screenshot-20220119-175100.png…]()

**Comment by MyonKeminta** [comment]
![origin_img_v2_9d24302f-d87a-4d63-abaf-58d946cf9b3g](https://user-images.githubusercontent.com/9948422/150110463-d5524059-c999-4434-b121-5e8d794ed388.png)
From @mayjiang0203 : A new case on 2022-01-19, GC resumes after being stuck for about 2 hours.

**Comment by hicqu** [comment]
https://github.com/tikv/tikv/pull/11922 should close this.

**Comment by MyonKeminta** [comment]
#11922 Optimizes gc_keys tasks in some scenarios. But if there's other cases that gc_keys costs too much time, we may still encounter this problem. Maybe we can close this issue by #11922 for now, and reopen if we found another case someday.
