### ISSUE TITLE
SpanDB

### ISSUE THREAD

**Issue by kokizzu** [tikv/tikv#11762]
Just information, that there's SpanDB claiming to be faster than RocksDB, might be can be inspiration for TiKV improvement

presentation: https://www.youtube.com/watch?v=a_eDVmh6CSc
code: https://github.com/SpanDB/SpanDB

**Comment by youjiali1995** [comment]
The idea of SpanDB is not new and "be faster than RocksDB" is not very difficult. Async I/O and high I/O depth are indispensable for max use of modern disk, e.g., NVMe SSD. These ideas are widely used in industry. The most famous one is https://github.com/scylladb/seastar which uses the idea since 2014 and it has lots of amazing functions.
