### ISSUE TITLE
Provide predictable stable write QPS under specified environment

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#11855]
### Is your feature request related to a problem? Please describe:

If we give enough pressure to the TiKV, the write QPS of TiKV is usually high at the begin and then drop as time pass by. It is not friendly to the user. If TiKV can provide predictable stable write QPS, it is a better experience for the user, although the stable QPS may lower than the max peak QPS.

### Describe the feature you'd like:

Add CPU Quota and write bandwidth quota for TiKV to provide predictable stable write QPS when the environment is specified like 4vCPU with a 4K IOPS 100MB/s bandwidth disk.

**Comment by tabokie** [comment]
The performance decline is mostly due to the increase of `physical works needed per user request` (tombstone reads, scattered regions, rocksdb write amplification). So it makes sense to directly limit user request instead of physical works. But I think it should probably be implemented in TiDB instead.
