### ISSUE TITLE
Add support for returning Table ID as a Column (EXTRA_PHYSICAL_TABLE_ID_COL_ID)

### ISSUE THREAD

**Issue by mjonss** [tikv/tikv#11888]
### Is your feature request related to a problem? Please describe:

In TiDB, table partitioning is implemented by having several physical tables presented as one logical table, where each partition is mapped to a Physical Table ID.

When dynamic prune mode for table partitioning was implemented, a single TableReader was used for all needed partitions, and sent a coprocessor requests which included multiple Physical Table ID ranges resulting in row data could come from several partitions in the result chunk. This works well for handling the data, but if there is an ongoing transaction or pessimistic locks are requested (SELECT FOR UPDATE/SelectLock) then each row needs to have which partition/physical table id it came from, to be able to lookup in TiDBs transaction buffer or to send a lock to TiKV (which both needs the Physical Table ID).

Since the Physical Table ID is encoded in the Key for each row in the KV Store, we could solve this problem if the Physical Table ID could be added as an extra column in the result chunk.

### Describe the feature you'd like:

Add a static column id '-3' / EXTRA_PHYSICAL_TABLE_ID_COL_ID, similar to int handle (-1) or EXTRA_PARTITION_ID_COL_ID (-2).
If a column with id -3 is requested, use the Table ID from the Key to fill in its 64 bit integer value. This should be done for both index and table reads.

### Describe alternatives you've considered:

- Add all partitioning columns to the read request and then recalculate which partition the row came from (a lot of overhead, both data/network wise and processing wise). Would not work for indexes not including all partitioning columns
- Get full key for each row and decode the table id on TiDB side. More data and processing overhead, similar implementation and no other use case yet.

### Teachability, Documentation, Adoption, Migration Strategy:

[Proof of Concept for TiDB UniStore](https://github.com/pingcap/tidb/pull/31634/files#diff-89dead167fcc4733d04c187d2bcd4ce4b987ecf204fed9ef9c15ead6b6604f07), see the unistore path code changes for details, `model.ExtraPhysTblID` is what is proposed to be `EXTRA_PHYSICAL_TABLE_ID_COL_ID` in TiKV.

**Comment by bb7133** [comment]
IMHO we don't have to return EXTRA_PHYSICAL_TABLE_ID_COL_ID for cases when locks are not needed. Would you consider how the 'request' proto can be updated to tell TiKV when the extra ID is requested?

Also, as a reference, the PR that introduces EXTRA_PHYSICAL_TABLE_ID_COL_ID is #8603.

**Comment by mjonss** [comment]
> IMHO we don't have to return EXTRA_PHYSICAL_TABLE_ID_COL_ID for cases when locks are not needed. Would you consider how the 'request' proto can be updated to tell TiKV when the extra ID is requested?

TIDB would only add the request for `EXTRA_PHYSICAL_TABLE_ID_COL_ID` when it is needed, so for an auto-commit query it would not add it to the requested columns.

> 
> Also, as a reference, the PR that introduces EXTRA_PHYSICAL_TABLE_ID_COL_ID is #8603.

That would be for the EXTRA_PARTITION_ID_COL_ID, which is a value in a global index 'row' referencing the table partition's physical table id where the table data is stored.

EXTRA_PHYSICAL_TABLE_ID_COL_ID is not yet implemented, which is what this Feature Request.

**Comment by bb7133** [comment]
Yes, it should be EXTRA_PARTITION_ID_COL_ID, my typo!

**Comment by bb7133** [comment]
> TIDB would only add the request for EXTRA_PHYSICAL_TABLE_ID_COL_ID when it is needed, so for an auto-commit query it would not add it to the requested columns.

I see, it was described here:

> If a column with id -3 is requested ...

Thanks!

**Comment by windtalker** [comment]
I have an implemention related question about this extra column:
After generate this column in `TableScan` or `IndexScan`, will this column be treated as a normal column or still a special column in the subsequent processing?
Consider the following query as a example:
`select count(id) from partition_table`
Then the cop request should be something like this
`TableScan(col: id, col: extra_physical_table_id_col_id) => aggregation`

If we treated as a normal column, then it's TiDB's job to rewrite the aggregation in cop request to `aggregation(agg_func: count(id), group_by: extra_physical_table_id_col_id)`
In this case I think current coprocessor protocal can support it directly.

If we treated as a special column, then the aggregation in cop request is `aggregation(agg_func: count(id), group by: )`
if we still wants to add `extra_physical_table_id_col_id` for each row returned by the aggregation executor, it will be a little tricky, since we need extra logical to append the `extra_physical_table_id_col_id` to the result chunk. And things become much more complex for TiFlash, because TiFlash support [MPP](https://github.com/pingcap/kvproto/blob/master/proto/mpp.proto#L34) and [BatchCoprocessor](https://github.com/pingcap/kvproto/blob/master/proto/coprocessor.proto#L73), it will batch all the regions in one TiFlash node into one request, that means the `TableScan` will read data from multiple partitions, and `aggregation` only return 1 row, so which `extra_physical_table_id_col_id` should be append to the return row in this case?

**Comment by bb7133** [comment]
@windtalker Thanks for pointing out this, I think the handle of the extra column should be treated as the special column(and we need to handle it very carefully).

It's not just about aggregation, if we decide to apply this proposal, other executors like `Limit`, `TopN` should be considered as well, which is non-trivial.

**Comment by mjonss** [comment]
@windtalker The only times the physical table id is needed is:
1) SelectLock used by `SELECT ... FOR UPDATE`, when TiDB needs to send pessimistic row lock to TiKV with the correct physical table id
2) In ongoing transaction in TiDB, where the physical table id per row is needed for checking against the TiDB local transaction buffer, if the row is changed within the transaction.
Both cases is for non-aggregated rows, similar to when ExtraHandleID (-1) is requested.

I did a quick test with `begin; insert into t values (1) ; select count(*) from t` and TiDB will not use any coprocessor for aggregation, but simply issue a full table scan and go through the UnionScan executor which merges the table scan data with the transaction buffer and then have a StreamAgg on top of the UnionScan. Same with LIMIT (it will add a limit on top of the UnionScan).

So I think it is OK to simply treat `extra_physical_table_id_col_id` as a normal column, and leave it up to TiDB handle for future aggregation/coprocessor support, where needed.

I assume this is similar to how the ExtraHandleID (-1) is handled by TiDB, so until we find something that would break this assumption, we should be OK to treat the different Extra*ID columns the same. I can see possible optimisation for partitions, but those could probably be done in TiDB instead (similar to how static pruning uses one TableReader per partition, it may be possible to do that dynamically as well for such future enhancements 🤷 )

@qw4990 Is that correct that for SelectLockExec and UnionScanExec it will not use any coprocessor aggregation etc. that would be a problem?

**Comment by windtalker** [comment]
> 1. ds to send pessimis

`Limit` and `TopN` should not be a big problem since it does not change the result schema, so if the input schema contains `extra_physical_table_id_col_id`, we can expect the output schema contains `extra_physical_table_id_col_id` too.
So if the coprocessor request is something like
`TableScan => TopN`
if the `TableScan` returns chunk with `extra_physical_table_id_col_id`, it is straightforward that the `TopN` returns chunk with `extra_physical_table_id_col_id`

**Comment by windtalker** [comment]
> begin; insert into t values (1) ; select count(*) from t

I think TiDB does not use coprocessor for aggregation because there are uncommited data for t, if you try 
`begin; select count(*) from t`
TiDB should push down aggregation to TiKV.

**Comment by mjonss** [comment]
> > begin; insert into t values (1) ; select count(*) from t
> 
> I think TiDB does not use coprocessor for aggregation because there are uncommited data for t, if you try `begin; select count(*) from t` TiDB should push down aggregation to TiKV.

Yes that is correct, and then we don't need the physical table id either. This is handled when there are uncommitted data [here](https://github.com/pingcap/tidb/blob/23f7e51ae01287fa7f811e1462d8987e4d7727a4/planner/core/logical_plan_builder.go#L4180-L4185). So I think it is OK.

**Comment by windtalker** [comment]
> > > begin; insert into t values (1) ; select count(*) from t
> > 
> > 
> > I think TiDB does not use coprocessor for aggregation because there are uncommited data for t, if you try `begin; select count(*) from t` TiDB should push down aggregation to TiKV.
> 
> Yes that is correct, and then we don't need the physical table id either. This is handled when there are uncommitted data [here](https://github.com/pingcap/tidb/blob/23f7e51ae01287fa7f811e1462d8987e4d7727a4/planner/core/logical_plan_builder.go#L4180-L4185). So I think it is OK.

So you mean when reading from a table, the physical table id is only needed if there is uncommitted data for that table? If yes, then things become quite simple because AFAIK if a table has dirty data, only TableScan/IndexScan/Selection can be pushed to the storage layer, we don't need to consider complex executor like `aggregation` and `join`.

**Comment by mjonss** [comment]
> So you mean when reading from a table, the physical table id is only needed if there is uncommitted data for that table? If yes, then things become quite simple because AFAIK if a table has dirty data, only TableScan/IndexScan/Selection can be pushed to the storage layer, we don't need to consider complex executor like `aggregation` and `join`.

Yes, the physical table id is only needed when there is either uncommitted data or there is a need to lock rows (like SELECT FOR UPDATE/SelectLock). So no need to consider complex executors like `aggregation` or `join`, since current TiDB planner would not request any of these complex coprocessor executors but handle it in TiDB after handling either transaction data (UnionScan that merges current query with the sessions non-committed transaction buffer) or setting a row lock (SelectLock executor in TiDB).
