### ISSUE TITLE
Take more than 5 hours to merge empty region after drop 6T data

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#12421]
### What version of TiKV are you using?

[2022/04/23 23:53:15.874 +08:00] [INFO] [client.go:376] ["Cluster version information"] [type=tikv] [version=6.0.0-alpha] [git_hash=ed7e1aa945d9ada9dc3ad3bd6420a9879d49ed44]

### What did you expect?
Since there are only less than 50G data during region merge, should not cost so much time.

### What did happened?
![image](https://user-images.githubusercontent.com/9443637/164956305-1db522c5-0471-45f3-bcdb-aeb0b575414d.png)
![image](https://user-images.githubusercontent.com/9443637/164956357-bb08fa26-f7e7-4890-80d7-29e64263a9e2.png)
![image](https://user-images.githubusercontent.com/9443637/164956361-65a32a38-2821-4d69-b77d-140087579671.png)

**Comment by tabokie** [comment]
Flamegraph shows TiKV is blocked on the RocksDB seeks in `clean_stale_ranges`, which is very possibly caused by tombstones.

![image](https://user-images.githubusercontent.com/27005812/164956468-613d9768-6214-48a2-b3f3-032d79f5360e.png)

Possible optimizations:
- Set the iter upper bound tighter in `delete_all_in_range_cf_by_ingest` (don't use the max_end_key)
- Use other deletion methods like delete_range when `max_skippable_internal_keys` is too high
