### ISSUE TITLE
v5.4.1: after restart all tikv/pd/tidb, one tikv continue report error "invalid store ID 0, not found"

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#12478]
### What version of TiKV are you using?

./tikv-server -V
 TiKV
Release Version:   5.4.0
Edition:           Community
Git Commit Hash:   44d2e7e8d86566b4b270c1ae39a4956e0f74a6e8
Git Commit Branch: heads/refs/tags/v5.4.1
UTC Build Time:    2022-04-29 06:35:41
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### Steps to reproduce

tcms test plan:
[endless-range-partition-oltp-sysbench-oltp-read-write@v5.4.1]

following tidb global config has been set.

tidb_partition_prune_mode='dynamic' ,  
tidb_replica_read='follower'

### What did you expect?
tikv should works fine.

### What did happened?
Tikv heartbeat with pd disconnect after that, no region message update from pd monitor.

tikv logs:
Status { code: 2-UNKNOWN, message: \"invalid store ID 0, not found\", details: [] }))"]
tikv.log:[2022/05/10 02:28:24.557 +00:00] [ERROR] [[util.rs:460](http://util.rs:460/)] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 0, not found\", details: [] }))"]
tikv.log:[2022/05/10 02:28:25.558 +00:00] [ERROR] [[util.rs:460](http://util.rs:460/)] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 0, not found\", details: [] }))"]
tikv.log:[2022/05/10 02:28:25.565 +00:00] [ERROR] [[util.rs:460](http://util.rs:460/)] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 0, not found\", details: [] }))"]
tikv.log:[2022/05/10 02:28:25.565 +00:00] [ERROR] [[raft_client.rs:749](http://raft_client.rs:749/)] ["resolve store address failed"] [err_code=KV:Unknown] [err="Other(\"[src/server/[resolve.rs:102](http://resolve.rs:102/)]: RpcFailure: 2-UNKNOWN invalid store ID 0, not found\")"] [msg="region_id: 134700 from_peer { id: 134703 store_id: 6 } to_peer {} region_epoch { conf_ver: 11 version: 1138 } extra_msg {}"] [store_id=0]
tikv.log:[2022/05/10 02:28:25.565 +00:00] [ERROR] [[util.rs:460](http://util.rs:460/)] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 0, not found\", details: [] }))"]

**Comment by 5kbpers** [comment]
Investigated that it was caused by a bug introduced by #8820.
#8820 introduces a mechanism that when a follower with no leader information wants to send a `ReadIndex`, it will try to query leader information from PD and send a "wakeup message" for waking up a hibernated leader.
https://github.com/tikv/tikv/blob/6d24c60586ac94ba24a16513b92989f63b8fced7/components/raftstore/src/store/peer.rs#L3597-L3599 https://github.com/tikv/tikv/blob/6d24c60586ac94ba24a16513b92989f63b8fced7/components/raftstore/src/store/fsm/peer.rs#L992-L999
The problem is sometimes PD doesn't have any knowledge about region leaders. Despite https://github.com/tikv/pd/pull/2591 starting to sync region leaders to PD followers, when all PD peers restarted then region leaders info could still get lost.
