### ISSUE TITLE
Generate grafana json template from code(Grafana as code)

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#12796]
## Development Task

It's always arduous to update grafana template as the grid position of json may change vastly everytime of adding just a new panel.

We can leverage [grafonnet](https://grafana.github.io/grafonnet-lib/) to generate the json template from code (here is a talk keynote
https://inuits.eu/pdfs/Grafana_as_Code.pdf). Then we don't need to struggle with the json changes, just to add a new query in code, and the grid position will be taken care of by the generator. The code would be like this, the noise of json is avoided and easy to reorganize and reuse same panel in different dashboards:

```jsonnet
local halfGridPos = {
    x: 0,
    y: 0,
    w: 12,
    h: 8,
}; // occupies half of a row

dashboard.new(
    title='Test-Cluster-TiKV-Details',
    schemaVersion=27,
)
.addRow(
    row.new('Cluster')
        .addPanel(
            graphPanel.new('The storage size per TiKV instance')
                .addTarget('sum(tikv_store_size_bytes{k8s_cluster="$k8s_cluster", tidb_cluster="$tidb_cluster", instance=~"$instance", type="used"}) by (instance)'),
            halfGridPos
        )
        .addPanel(
            graphPanel.new('Approximate Region size')
                .addTarget('sum(tikv_raftstore_region_size_sum{k8s_cluster="$k8s_cluster", tidb_cluster="$tidb_cluster", instance=~"$instance"}) by (instance)'),
            halfGridPos
        )
        .addPanel(..., halfGridPos)
)
.addRow(
    row.new(title='Errors')
        .addPanel(..., halfGridPos)
)
.addRow(
    row.new(title='Server')
        .addPanel(..., halfGridPos)
)
```

**Comment by tabokie** [comment]
Looks promising.

**Comment by breezewish** [comment]
I think the major problem comes from that we don't have a clear guideline about how to update the metrics JSON. 

After https://github.com/pingcap/tiup/pull/1920 is merged, a standard procedure to update the Grafana JSON can be greatly simplified to:

1. Start a Grafana (e.g. using TiUP Playground).
2. Modify the Grafana Dashboard using the What-You-See-Is-What-You-Get Grafana UI.
3. Click "Share" → "Export", turn on "Export for sharing externally" and then click "View JSON".
   <img width="908" alt="image" src="https://user-images.githubusercontent.com/1916485/173536953-0f66f13d-3a7a-47d5-8c9a-88c154689a4f.png">
6. Copy the entire content into the json file in the repository.
7. Commit!

Note that, even for code generated dashboards, you still need to perform step 1 and step 2 in order to see whether your expression is correct, and whether the visualization is nice to view.

**Comment by Connor1996** [comment]
@breezewish That's how we does now. But the cluster name will be renamed to a specified one after export. We still needs to replace the cluster name manually.

And different version Grafana dumps different json causing it changes vastly though I just simply change a query.

**Comment by Connor1996** [comment]
And here is a case that we need to rechange in grafana UI and reexport the metrics when picking PR to other branches, but code doesn't this problem and easy to review.

**Comment by Connor1996** [comment]
> I agree that this causes the diff hard to view. The downside of the codegen will be, you need to manually craft how the panel is constructed, when you have adjusted it well in the UI. For example, you may set multiple axises, changing decimals, or even different or complicated graph types (like Heatmap) in order to make the chart looks nice. Now, how would I write the code to generate this graph? This can be a very difficult problem.

I agree, that's a concern for me as well. So I didn't quite hurry on this task, need to think twice.

**Comment by Connor1996** [comment]
@breezewish https://github.com/pingcap/tiup/pull/1920 it seems that it only affects the playground?

**Comment by breezewish** [comment]
There is an existing experiment in TiDB, as: https://github.com/pingcap/tidb/blob/master/metrics/grafana/tidb_summary.jsonnet

Personally I would consider it to be an example of failure, because the visualization becomes very limited. There are only line-charts now. Of course no one attempted to change other Grafana JSONs, as the visualization is too complicated and the codegen is hard to craft (more precisely, too many APIs, hard to learn).

**Comment by Connor1996** [comment]
Oh, don't know TiDB has tried it before. 

When adding new types of metrics we can use Grafana UI to dump the json first, then you would know the value for each json key and transfer it to code.

**Comment by breezewish** [comment]
> @breezewish [pingcap/tiup#1920](https://github.com/pingcap/tiup/pull/1920) it seems that it only affects the playground?

Yes, currently I'm thinking that using playground should be easy and sufficient enough, to be used to make Grafana Dashboard changes. Not sure whether TiUP Cluster is really necessary.

> When adding new types of metrics we can use Grafana UI to dump the json first, then you would know the value for each json key and transfer it to code.

According the current TiDB's jsonnet file I'm afraid it is a hard work. The jsonnet API is a higher encapsulation, not directly 1:1 mapped to the JSON.

**Comment by breezewish** [comment]
> But for normally deployed cluster, the cluster name is replaced with tiup cluster name

Yes, it should be intentional, for normal users it would be better to see "MyCluster-TiFlash" instead of "Test-Cluster-TiFlash" I think.

This limits that we should not modify dashboard (and contribute it to TiKV code base) using normal clusters. We should always modify the dashboard using a TiUP Playground deployed cluster. Considering TiUP Playground is much easier to use than TiUP Cluster, I think this should be fine. What do you think?

**Comment by Connor1996** [comment]
When developing features, we usually need to deploy a normal cluster with patched binary to add metrics and check if everything works as expected. Playground doesn't meet the demand.

**Comment by breezewish** [comment]
> When developing features, we usually need to deploy a normal cluster with patched binary to add metrics and check if everything works as expected. Playground doesn't meet the demand.

How about something like:

```shell
tiup playground nightly --db.binpath ~/Work/tidb/bin/tidb-server
tiup playground v5.4.1 --db.binpath ~/Work/tidb/bin/tidb-server
```

I used to use this arguments (there are also arguments for TiKV, TiFlash and PD as well) so that my local patched one can be started. In contrary, TiUP Cluster is hard to use in my MacOS.

**Comment by Connor1996** [comment]
The key point is we seldom deploy a playground to testify features, cause usually it's performance critical. Though if we have a way to dump json like playground that cluster name is not changed and no need to tweak dumped json with mental burden, I agree to only use grafana UI.
