### ISSUE TITLE
TiKV crash when use 2pc commit and batchGet

### ISSUE THREAD

**Issue by bxq2011hust** [tikv/tikv#12926]
### What version of TiKV are you using?
v5.4.0

### What operating system and CPU are you using?

macOS 12.4 Apple M1

### Steps to reproduce
```bash
git clone -b dev-3.0.0-rc4 https://github.com/bxq2011hust/tikv-client-c.git 
mkdir build && cd build
cmake -DENABLE_TESTS=on ..
./src/test/real_tikv_test/bcos_2pc_test --gtest_filter="*bcosCommmit_100"
```

### What did you expect?

works well

### What did happened?

![image](https://user-images.githubusercontent.com/15418097/176164004-44406722-bff4-4e01-bfa2-5474bc3e4a20.png)

if set [`resolved-ts.enable=false`](https://docs.pingcap.com/zh/tidb/v5.4/tikv-configuration-file#resolved-ts), tikv will not crash

**Comment by sticnarf** [comment]
@5kbpers Do you have any ideas about this assertion?

**Comment by 5kbpers** [comment]
set `resolved-ts.enable` to `false` if using TXN KV.

**Comment by sticnarf** [comment]
@bxq2011hust  Well, I think the problem here is that you must make sure there are no duplicated keys in a prewrite request. 
From your program, it's possible that two `rand()` produces the same number and generate same keys:

https://github.com/bxq2011hust/tikv-client-c/blob/dev-3.0.0-rc4/src/test/real_tikv_test/bcos_2pc_test.cc#L157
