### ISSUE TITLE
one az is isolated from other az networks, and the service is unavailable for 4 minutes

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#12966]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.1.0
Edition:           Community
Git Commit Hash:   080d086832ae5ce2495352dccaf8df5d40f30687
Git Commit Branch: heads/refs/tags/v6.1.0
UTC Build Time:    2022-06-10 11:22:39
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What operating system and CPU are you using?
8core、32g

### Steps to reproduce
inject one az is isolated from other az networks

### What did you expect?
the service is available

### What did happened?
the service is unavailable for 4 minutes
![image](https://user-images.githubusercontent.com/84712107/177475459-cb9b016e-8388-4b4c-86a0-74c22d7e64b7.png)

more info see https://pingcap.feishu.cn/wiki/wikcnzK33Ck6q1BQldXOnMUMvPc

**Comment by cosven** [comment]
This issue is investigation. I'll update this issue when there is any update.

/assign @cosven

**Comment by cosven** [comment]
This bug can affects all the old versions. However, since this will only be fixed in latest LTS version (v6.1) and lator versions, so I add and remove some labels.

/affects-6.1
/remove-may-affects-6.0
/remove-may-affects-5.4
/remove-may-affects-5.3
/remove-may-affects-5.2
/remove-may-affects-5.1
/remove-may-affects-5.0
/remove-may-affects-4.0
/remove-affects-6.2
