### ISSUE TITLE
Storage pool regression on AWS EC2 instance type i3.4xlarge

### ISSUE THREAD

**Issue by Yui-Song** [tikv/tikv#13280]
### What version of TiKV are you using?

version:6.2.0-alpha,	commit 7824699f4e05feb3eb37b12265ecc1e26511a4d7

### What operating system and CPU are you using?

AWS EC2 instance type i3.4xlarge with Centos 7
```
Linux ip-172-31-25-210.us-west-2.compute.internal 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
processor       : 15
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
stepping        : 1
microcode       : 0xb00003e
cpu MHz         : 2632.000
cache size      : 46080 KB
physical id     : 0
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 15
initial apicid  : 15
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
bogomips        : 4600.01
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

### Steps to reproduce

compare the performance of TiDB v6.1.0 and v6.2.0 on sysbench oltp_point_select 900 threads with config
`readpool.storage.normal-concurrency: 10`
```
 sysbench oltp_point_select run --report-interval=10 --rand-type=uniform --mysql-db=sysbench \
 --mysql-host=127.0.0.1 --mysql-port=3390 --mysql-user=root --time=600 --threads=900 \
 --tables=16 --table-size=10000000 --mysql-ignore-errors=9007 
```

### What did you expect?
The performance of the two versions is similar. 

### What did happened?
There was a 27.46% regression in v6.2.0.

version | config | threads | QPS
-- | -- | -- | --
6.1.0 | readpool.storage.normal-concurrency: 10 | 900 | 417172.3
6.2.0 | readpool.storage.normal-concurrency: 10 | 900 | 301870.72
6.1.0 | readpool.storage.normal-concurrency: 10 | 300 | 262053.57
6.2.0 | readpool.storage.normal-concurrency: 10 | 300 | 259545.54

**Comment by sticnarf** [comment]
I use Linux `perf` to investigate the issue on AWS i3 instances and find something unusual. `clock_gettime` needs to do real syscalls instead of just cheap vdso:

![image](https://user-images.githubusercontent.com/17217495/184805426-3a9d69da-132a-4ae5-a61d-e706c030729f.png)

This means `Instant::now` is really expensive on these machines. That's why a lot of recent pull requests that change `coarse_now` to `now` or add new `Instant::now` calls are reported to cause performance regressions on AWS EC3 i3 instances.

AWS i3 instances use xen virtualization. So the default clock source is `xen`. In this mode, it needs a real syscall to get monotonic now. 

```
$ cat /sys/devices/system/clocksource/clocksource0/current_clocksource
xen
```

After changing the clock source to `tsc`, `clock_gettime` no longer needs to do a real syscall.

```
$ echo tsc | sudo tee /sys/devices/system/clocksource/clocksource0/current_clocksource
```

And then, I cannot find the performance regression caused by #12441.

Using `tsc` as the clock source is also the best practice recommended by AWS: https://aws.amazon.com/cn/premiumsupport/knowledge-center/manage-ec2-linux-clock-source/

**Comment by BusyJay** [comment]
Can this difference be observed by builtin profiling?

**Comment by sticnarf** [comment]
> Can this difference be observed by builtin profiling?

No, the built-in profiling puts glibc and vdso in the blocklist because the unwinding implementation provided by libgcc cannot handle them well. So the syscalls are not included in the built-in flamegraph.
