### ISSUE TITLE
resolved_ts:  IngestSST do not update the tracked_index

### ISSUE THREAD

**Issue by hehechen** [tikv/tikv#13353]
### Is your feature request related to a problem? Please describe:

In [`group_row_changes`](https://github.com/tikv/tikv/blob/0030aeb90a840140a935fbb0181b6a62b5e680b3/components/resolved_ts/src/cmd.rs#L193), only update tracked_index of the `CmdType::Put `and `CmdType::Delete`, tracked_index not updated in IngestSST and [1PC](https://github.com/tikv/tikv/blob/6dcd0b3d66945583a133e60838533a5d12b3a487/components/resolved_ts/src/endpoint.rs#L193) scenarios.

TiFlash needs to use safe_ts to determine whether the peer's data synchronization progress is far behind the leader, so if the tracked_index is not updated in IngestSST scenario, the result is inaccurate. (ref: https://github.com/pingcap/tiflash/issues/4902)

### Describe the feature you'd like:

Update tracked_index in `IngestSST` and 1PC scenarios.

**Comment by NingLin-P** [comment]
It may be okay to ignore `IngestSST` because only followers will apply this command (maybe leader that not yet apply to its term also do), and `tracked_index` & `resolved_ts` is only meaningful for the leader and the leader will initialize them after it has applied to its term.

The 1PC case may indeed be a problem. As if there are only 1PC write commands, the `resolved_ts` will ever increase but the `tracked_index` does not which means peers that do not apply any new command can still handle read requests with newer ts. 

Although 1PC does not have any locks thus `resolved_ts` can be updated with or without 1PC being tracked, just updating the `tracked_index` for 1PC will be enough, because the ts used for update `resolved_ts` is bounded by `cm.global_min_lock_ts` and the following code ensures 1PC is being tracked before its lock in the concurrency manager is released (which may affect `cm.global_min_lock_ts`): 
https://github.com/tikv/tikv/blob/8c93b91fea7396b9261551297d1bfa037c82e605/components/raftstore/src/store/fsm/apply.rs#L564-L575

Not quite sure if this case exists but if it does better add some test case for it, in case incoming change breaks the assumption here.

**Comment by hehechen** [comment]
> It may be okay to ignore `IngestSST` because only followers will apply this command (maybe leader that not yet apply to its term also do), and `tracked_index` & `resolved_ts` is only meaningful for the leader and the leader will initialize them after it has applied to its term.
> 
> The 1PC case may indeed be a problem. As if there are only 1PC write commands, the `resolved_ts` will ever increase but the `tracked_index` does not which means peers that do not apply any new command can still handle read requests with newer ts.
> 
> Although 1PC does not have any locks thus `resolved_ts` can be updated with or without 1PC being tracked, just updating the `tracked_index` for 1PC will be enough, because the ts used for update `resolved_ts` is bounded by `cm.global_min_lock_ts` and the following code ensures 1PC is being tracked before its lock in the concurrency manager is released (which may affect `cm.global_min_lock_ts`):
> 
> https://github.com/tikv/tikv/blob/8c93b91fea7396b9261551297d1bfa037c82e605/components/raftstore/src/store/fsm/apply.rs#L564-L575
> 
> Not quite sure if this case exists but if it does better add some test case for it, in case incoming change breaks the assumption here.

It's OK to ignore `IngestSST` in existing scenarios, but for the [new TiFlash feature](https://github.com/pingcap/tiflash/issues/4902), TiFlash needs to use safe_ts to determine whether the peer's data synchronization progress is far behind the leader, so if the tracked_index is not updated in IngestSST scenario, the result is inaccurate.
Tracking `IngestSST` has little effect on TiKV, but is helpful for TiFlash, so I think adding tracking for `IngestSST` is OK.

**Comment by NingLin-P** [comment]
I didn't have a detailed look at the new TiFlash feature and not sure if this change is necessary but just mentioning that `tracked_index` is only meaningful for the leader and only maintained by the leader, what other peers use to determine their `safe_ts` is their own `apply_index`

**Comment by NingLin-P** [comment]
> It may be okay to ignore IngestSST because only followers will apply this command (maybe leader that not yet apply to its term also do)

Oh, perhaps I do have confused with `IngestSST`, leader may also apply this command thus indeed need to track it.

**Comment by hehechen** [comment]
> I didn't have a detailed look at the new TiFlash feature thus not sure if this change is necessary but just mentioning that `tracked_index` is only meaningful for the leader and only maintained by the leader, what other peers use to determine their `safe_ts` is their own `apply_index`

Leader will send <tracked_index, safe_ts> to follower/learner. If the tracked_index not be updated in `IngestSST` scenario, learner will update `safe_ts` (because leader will update safe_ts from PD) even the data synchronization progress is far behind the leader.
