### ISSUE TITLE
[dynamic regions] Need a way to figure out whether dynamic region is used

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#14161]
## Development Task

For now we can only check that by looking into logs or using SQL. It's more useful if we can tell it from metrics directly.

**Comment by tonyxuqqi** [comment]
There's a few indirect ways to tell if MultiRocks is used or not. 
1) memtable size. MultiRocksDB's memtable size metrics is much bigger (around GB level) while single rocksdb is just < 500MB
2) TiKV Details->Cluster->MBps. MultiRocksDB does not have WAL, so the write volumes in that metrics is very small, while single rocksdb should have much bigger volumes. 

3) store size & region count. 

So probably TiKV side we have good enough metrics to tell. However, I think probably PD needs this information as well so that it can adapt some default parameters better for multi-rocksdb. Maybe we can show it in PD's metrics.

**Comment by tonyxuqqi** [comment]
probably need to have explicit flag in PD
