### ISSUE TITLE
【witness】restart one tikv every 20min，tpcc report 9005 at  certain fault

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14217]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.6.0-alpha
Edition:           Community
Git Commit Hash:   ee00d70008562b45bafb0dcd88d70520a18fa742
Git Commit Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time:    2023-02-08 11:56:04
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-02-09T19:04:48.004+0800	INFO	k8s/client.go:132

### What operating system and CPU are you using?
8core/16G

### Steps to reproduce
https://tcms.pingcap.net/dashboard/executions/plan/1620181
restart one tikv every 20min
[2023/02/09 20:36:34.535 +08:00] [INFO] [util.go:729] ["begin to restart tikv_2."]

### What did you expect?
no 9005 error

### What did happened?
tpcc report 9005 at  certain fault

[2023-02-09 12:40:58] execute run failed, err exec SELECT c_id FROM customer WHERE c_w_id = ? AND c_d_id = ? AND c_last = ? ORDER BY c_first failed Error 9005: Region is unavailable

**Comment by ethercflow** [comment]
From log:

T0 Leader, witness, voter
T1 Leader, witness learner, voter
T2 Leader, non-witness learner, voter
T3 non-witness learner applied snapshot, but during this period, a snapshot is requested again (in order to prevent the first request from failing, it will be retried, and a judgment should be added here to determine whether the snapshot is being applied), and the leader is notified that the snapshot has been applied;
T4 The leader receives the non-witness notification, thinks it is no longer pending, and reports to pd
T5 After receiving the notification from the leader, pd thinks that the switch to non-witness has succeeded, and sends the next op
T6 pd send non-witness learner -> Voter;
T7 The leader executes conf change, thinking that non-witness has become a Voter, but in fact non-witness is still a learner and is executing snapshot;
T8 leader, Voter (actually still learner), witness learner

Resulting in 3 nodes, 2 leaners, re-election, and finally no leader returns 9005
