### ISSUE TITLE
【witness】inject one tikv network loss for in 10min repeatly，for certain inject and after recover fault，raft log lag is more and more

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14228]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.7.0-alpha
Edition:           Community
Git Commit Hash:   7a474f2ef4a98ba4a61b81d526f6b01970f993b3
Git Commit Branch: master
UTC Build Time:    2023-02-14 09:08:00
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-02-14T18:42:34.403+0800	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129

### What operating system and CPU are you using?
8c/32G

### Steps to reproduce
https://tcms.pingcap.net/dashboard/executions/plan/1621081
inject one tikv network loss for in 10min repeatly
check raft log lag for every inject

### What did you expect?
raft log lag can catch up in 3h

### What did happened?
for certain inject and after recover fault，raft log lag is more and more
![image](https://user-images.githubusercontent.com/84712107/218934107-92c91a65-f0b8-4e1a-9f11-da245c2f85c6.png)

**Comment by ethercflow** [comment]
Failed to notify the leader after the witness applied the empty snapshot. Then the leader continues to try the transfer leader behavior for several hours and fails (because the status of the witness  is `ProgressState::Snapshot`), and the witness peer keeps as pending

![image](https://user-images.githubusercontent.com/38067786/219615715-913af8ce-96d1-4fa4-b465-b6df67934cb0.png)

![image](https://user-images.githubusercontent.com/38067786/219615546-711845d0-97b3-49bf-93d1-d25e827e967f.png)

![image](https://user-images.githubusercontent.com/38067786/219617206-469c7f9a-5213-4545-b0ce-022d16d77cbb.png)


![image](https://user-images.githubusercontent.com/38067786/219616820-1702950a-d85f-4ed8-8a27-a0c30e10bfb9.png)

![image](https://user-images.githubusercontent.com/38067786/219617517-5ad50a38-ceca-4382-b834-83a16bd781f6.png)
