### ISSUE TITLE
[Dynamic Regions] QPS drop form 28k to 1k with workload error code 9005 during one tikv down 

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14315]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.7.0-alpha
Edition:           Community
Git Commit Hash:   192dff638d05724759e3dee642639a86b20e4565
Git Commit Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:    2023-02-28 09:44:19
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What operating system and CPU are you using?
8c/16g

### Steps to reproduce
1、run tpcc 
go-tpc tpcc run -D tpcc --host tc-tidb.glh-master-2s274 -P4000 --warehouses 1000 -T 64 --ignore-error '2013,1213,1105,1205,8022,8028,9004,9007,1062' --password ''"
2、inject one tikv down for 10m

### What did you expect?
qps can recover within 2min

### What did happened?
logs：http://minio.pingcap.net:38888/buckets/test-infra-testground/browse/YXJjaGl2ZS9nbGgtbWFzdGVyLTJzMjc0
clinic：https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7205420345768410023?from=1677663000&to=1677664550
QPS drop form 28k to 1k during inject one tikv down
![image](https://user-images.githubusercontent.com/84712107/222104268-8848f5c1-1d6a-412c-bcb7-25317d1cc2e6.png)
![image](https://user-images.githubusercontent.com/84712107/222104395-991b4e92-eb10-4f45-aa28-13613b03048e.png)

**Comment by Lily2025** [comment]
cluster is unavailable after this issue occurrence even if the injected failure is recovered，report error [always
![8ea068c5-edde-44f1-92a0-060407eab477](https://user-images.githubusercontent.com/84712107/222322066-afab4c6e-5c94-4af3-b122-7af8bf529b34.jpeg)
![16de50c7-c201-4270-bcbc-f70cbd3718a9](https://user-images.githubusercontent.com/84712107/222322079-7846a66f-7fc2-441b-891d-ebb7cfcf8339.jpeg)

**Comment by BusyJay** [comment]
Should be fixed by #14275

**Comment by SpadeA-Tang** [comment]
The cause of this issue is that there was a race condition between registering mailbox and scheduling some ticks including raft tick (it has been fixed by #14275). The race condition means some peers may not schedule raft tick successfully as the mailbox has not been registered at that time. Some raft processes will not be proceeded without raft tick including election, so after they recognize a leader, they will be in lease status forever (`self.leader != INVALID_ID && self.election_elapsed < self.election_timeout`). Now, if the node of their leader restarts, their pre-leader will start to compaign after some while, but the votes will be rejected by them (in lease status). So two peers of the same region falling in this condition will lead the region unavailable forever just like this.
