### ISSUE TITLE
[Dynamic Regions] max_prefill_count conflicts with large purge-threshhold

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14468]
### What version of TiKV are you using?

v7.0

### What operating system and CPU are you using?

x86
### Steps to reproduce

3pd(8c) + 3tidb(32c) + 3tikv(32c)

### What did you expect?
multiRocksDB out performance baseline

### What did happened?
multiRocksDB query P99 18ms
baseline query P99 ~10ms

 raft-engine.purge-threshold 200GB conflicts with prefill, because max_prefill_count = 96, this is why the first 5 minutes is good performance, when the file count grows over 96, recycling log does not take effects and performance degrades by around 4x.
![image](https://user-images.githubusercontent.com/2316425/227967567-aa51060d-669e-4ccd-87eb-bb7b8daa8600.png)

**Comment by LykxSassinator** [comment]
This root cause of this issue is that the max size of `raft-engine.prefill-for-recycle` is 12GB by default. This makes the max capacity of prefilled recycled files is 12 GB / 128MB(`target-file-size`) = 96.

In this test case, the `purge-threshold` is set to be 200GB (expect at least 200GB / 128MB = 1600 files for making log recycling effective), massively exceeding the expectation of `prefill-for-recycle` function.
