### ISSUE TITLE
[Read-Only Replica] tikv oom when network delay between read-only instance and tispark

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14759]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.5.1
Edition:           Community
Git Commit Hash:   bc3e311060be390c16c66172ae86c9f34a28c72f
Git Commit Branch: heads/refs/tags/v6.5.1
UTC Build Time:    2023-03-04 06:28:22
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-05-17T08:51:01.761+0800	INFO	k8s/client.go:132

### What operating system and CPU are you using?
16c/64g

### Steps to reproduce
1. Record the current QPS, latency, and other information of the load. 
2. Use TiSpark to export data to S3 (select * from table), and during the export process, simulate a network latency of 20ms for one read-only instance. Let the latency persist for 10 minutes before recovering. Observe the workload metrics (QPS, latency) of the system and the behavior of the TiSpark export task.

### What did you expect?
all instance are normal

### What did happened?
 tikv oom twice
![image](https://github.com/tikv/tikv/assets/84712107/68a2cdfe-8d4d-43e5-8a29-bb837117198c)
![image](https://github.com/tikv/tikv/assets/84712107/67e36da8-b19c-41e4-92fa-3c93eff329d4)

**Comment by v01dstar** [comment]
This kind of OOM is expected. Since the coprocessor tasks were huge, increasing the latency increased the in flight tasks, which resulted in OOM, it was a "common" instead of "specific" OOM. To solve this kind of issue fundamentally, we need to bring proactive memory management mechanism into TiKV, which is already considered but not scheduled yet. Fortunately, this issue has some mitigations such as: 1. changing the server instance type, more memory less CPU. 2. reducing the client's traffic. etc. Due to above reasons, I am closing this issue for better organizing and planing.
