### ISSUE TITLE
Reduce compaction job size

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#15058]
## Development Task
Today we control the compaction job size by https://docs.pingcap.com/tidb/dev/tikv-configuration-file#compaction-guard-min-output-file-size. By default this value is 8MB, but when doing lightning, it could still lead to long time compaction (#15036).
Further reducing the compaction-guard-min-output-file-size from 1MB to smaller size may have other side effects and also cannot solve the problem completely. 

To completely solve the problem, we should limit the SST size generated by compaction in a way that it guarantees not lead to large compaction. That means when generating SST, we should not only check the SST size itself, but also the data size of the range in next level.

**Comment by YuJuncen** [comment]
I'm not sure whether there will be a universal solution. The recent issue https://github.com/facebook/rocksdb/issues/11502 shows, the huge compaction can be triggered via a TTL compaction, if there is a file with a little KV entries but a wide range of key:
```
|--------(little)----------| (L5)
|--|--|--|--|--|--|--|--|--| (L6)
^                          ^
+-(A huge bundle of Files)-+
```
In normal cases, I think there won't be a compaction until there are enough writes. But TTL compaction triggers. A simple solution is focusing on the TTL & periodical compaction: when we have detected it will trigger a huge compaction, we can trigger a *in-level compaction*. (If I have rightly understood the goal of TTL compaction: triggering GC and compaction filters, in-level compaction will fit our goal.)

And for the tidb-lightning case, it seems things goes more complex: it looks like we have choose too many L0 files for a compaction(Perhaps we can choose less files for the compaction, but I haven't check the code.).

Also cc @tabokie, do you have some good ideas or suggestions?

**Comment by tabokie** [comment]
What about the old design? It's as simple as adding a new member variable `overlap_size_with_next_level` to `SubcompactionState`. And pass that variable to `ShouldPartition`. TiKV can then split the file accordingly.

> in-level compaction

It doesn't change the situation because `creation_time` is the oldest of input file creation time. It basically never jumps back. And there're other ways to pick this file as compaction input. Manual compaction, for example.

> Perhaps we can choose less files for the compaction

RocksDB chooses the largest L0 and all other L0 that overlaps with it into a compaction. You might be able to work around it somehow but I don't think it will be easy to cover all possible cases of large compaction.

**Comment by YuJuncen** [comment]
I think the origin design probably works for the https://github.com/facebook/rocksdb/issues/11502. 

And for #10536, it may not have significant effect. I have checked the metrics again, it shows the pending compaction bytes is relative to the L4 (logically L1) files:

<img width="932" alt="image" src="https://github.com/tikv/tikv/assets/36239017/e30cbcae-480f-4824-9c0d-1f425e1628e1">

Due to lack of the rocksdb's log, I cannot figure out what actually what happened. But I guess:
1. There are many L0 files ingested, and no write stall triggered.
2. Some of them (probably a wide subset of them) has been compacted to L4.
<img width="936" alt="image" src="https://github.com/tikv/tikv/assets/36239017/e17d2f9d-d067-42fd-bff0-84a2e0e6630d">
3. So, there will be many data in L4. (I'm not sure whether there is a metric of SST size of each level, but the number of files somehow implies that.)
<img width="925" alt="image" src="https://github.com/tikv/tikv/assets/36239017/28f09707-e788-4942-8a1e-08a73b69ffe1">
4. Then... Files in L0 may be compacted with the large L4 -- according to the workload, probably the whole table's new data.

It looks pretty like writing a bulk of data into rocksdb without any flow control -- we are suffering from write amplification and the resource finally runs out. Just splitting SSTs may not be helpful for this scenario.

**Comment by YuJuncen** [comment]
For a better intra-L0 compaction and L0 to L4 compaction, dynamically splitting L0 into many sub-levels like [pebble did](https://www.cockroachlabs.com/blog/bulk-data-import/) may be helpful. But that would be a really huge project, as "it won't be easy".

**Comment by YuJuncen** [comment]
Also note that when the wide ranged file appear before the L6 size grows (i.e., we started tidb-lightning after the wide file appearing in L5.), the origin design cannot help -- even this is a rare case.

**Comment by YuJuncen** [comment]
And for the original design, there remained a tiny problem: how we decide whether to split a SST file or not? 
A naïve algorithm is, when the next level size is larger than a threshold, we always trigger the split by region logic. (!) But it seems hard to choose right threshold.
Or, we can assume the write patten should be similar over time, so we trigger the partition in the region boundary `x` times that making each SST contains generally even **number** of regions. (where `x = next_level_size / max_compaction_size`)
Or, we can require the approx. size for raft store (Or RocksDB, which providing something like `next_level_size_till_now`) and try to split once the size reaches `max_compaction_size`.
How do you think about the strategy? @tabokie @tonyxuqqi

**Comment by tabokie** [comment]
The decision should be made based on the file boundaries of next level. You can pass them in when creating partitioner.

**Comment by YuJuncen** [comment]
> The decision should be made based on the file boundaries of next level. You can pass them in when creating partitioner.

Maybe along with the size of each file? I guess the boundary will probably be similar with the region boundary.
