### ISSUE TITLE
[dr-autosync] tikv flashback hung more than 12h

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#15107]
### What version of TiKV are you using?

6.5.3

### Steps to reproduce

Try to recover tidb cluster after switching from sync_recovery mode to backup dc, after do online recovery succeeded, do flashback to backup to min resolved ts.

### What did you expect?
flashback return and succeeded.

### What did happened?
![460d52d8-0137-45ea-a4bb-fa0c5885de2b](https://github.com/tikv/tikv/assets/9443637/38fdb391-a147-48db-a05a-8e1bc1130c4d)

**Comment by mayjiang0203** [comment]
/severity critical
Mark it critical since it blocks ACID recovery after switching during sync_recovery. 
Will lower its severity if we can find a w/a.

**Comment by HuSharp** [comment]
https://github.com/tikv/tikv/blob/master/src/server/debug.rs#L1082-L1084 At finish flashback state, if any future returns an error halfway. 
Through the https://github.com/tikv/tikv/blob/master/cmd/tikv-ctl/src/main.rs#L941-L947  execution, it will continue and retry.
And then since the previous region has already executed the finish flashback, it will always return not in flashback state, and then continue triggering the retry continue, so introduce a dead loop.

**Comment by JmPotato** [comment]
#15219 is also part of the reason that makes the phase-2 flashback keep failing.
