### ISSUE TITLE
[regexp lib] TiKV's regexp is inconsistent with that of Tidb

### ISSUE THREAD

**Issue by knull-cn** [tikv/tikv#15478]
### What version of TiKV are you using?

v6.5.x, v7.1.x

### What operating system and CPU are you using?

1tikv (72c/385g)

### Steps to reproduce

```SQL
create table TT (str varchar(1000));
insert into TT (str) values('^/home/ap/ncbs/file/output/fa/xbrl/\d{4}([0]{1}[1-9]{1}|[1]{1}[012]{1})([0]{1}[1-9]{1}|[12]{1}\d{1}|[3]{1}[01]{1})/IVSR_HOLD_FNDLOT_PERCN_\d{2}\_\d{8}\.txt$');
select 1 from TT where 'abc' regexp str;
```

### What did you expect?
no error

### What did happened?
![image](https://github.com/tikv/tikv/assets/5057528/2694cedc-b8c4-4b9c-82f7-7c3c232d4dec)

**Comment by knull-cn** [comment]
same query run on tidb v6.1.1 was correct
because the regexp was run on tidb-server at v6.1.1；and  pushdown to tikv v6.5.x
means , regexp was different between on golang and rust

**Comment by gengliqi** [comment]
The escape `\` for `\_` is useless. 
So the reason is as https://github.com/rust-lang/regex/issues/497 said,
```
Inconsequential escapes are not allowed.
```

Most of the behavior between the regexp library of Golang and Rust is the same, but a few behaviors like this one are different. Only when we unify the three compute engines can all behaviors be truly consistent.

**Comment by zanmato1984** [comment]
This seems a duplicate of https://github.com/pingcap/tidb/issues/48360

Let's close this one and track the issue in the other.
