### ISSUE TITLE
gc can not work when disk capacity is near full

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#15846]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.5.4
Edition:           Community
Git Commit Hash:   20ccb6ebe5b738ca9a86bcce8e38caaa9079960a
Git Commit Branch: heads/refs/tags/v6.5.0
UTC Build Time:    2023-09-04 02:44:07
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run mussel workload with stale read and closest-replicas 
2、enable ttl
3、disk capacity of tikv is near full
![image](https://github.com/tikv/tikv/assets/84712107/6732801c-b594-4412-8313-84305a94c3b9)

### What did you expect?
gc can work so that release some capacity

### What did happened?
write failed and gc can not work

**Comment by LykxSassinator** [comment]
This case shows that the whole cluster has already encountered into a corner case where both the memory and the disk usage have reached the limit.

The root cause of this issue has two main reasons:
* Disk almost full. Instances `tc-tikv-3`, `tc-tikv-1` and `tc-tikv-4` are both under the `DiskUsage::AlmostFull` status, which will reject the normal write operations.
* Too low limitation of memory triggers the "reject" on raft messages. Too low `block-cache` setting with `1MB`, causing the limit of `memory-usage-limit` is ~1MB.
![f8ebe888-2e41-4e71-bae7-241ceb40009e](https://github.com/tikv/tikv/assets/18441614/b4eed99c-a748-47c1-a8e0-cc7481d8dc23)
And this makes the limit on rejecting raft messages triggered by [reject-memory-usage-ratio](https://github.com/tikv/tikv/pull/10555/files) easier to meet the requirement.
![image](https://github.com/tikv/tikv/assets/18441614/4b0913c4-dbed-45f1-b025-9d13b65599a9)

With these reasons, there exists massive pending commands cannot be executed in the mentioned nodes. And when TiDB tried to trigger a `GC` request to release the stale space, it will failed on getting the basic infos from the System Catalog with the timeout message `9005: region is unavailable`.
![img_v3_024j_9b250028-d2e7-415f-9a55-980abce905eg](https://github.com/tikv/tikv/assets/18441614/75b905b9-2ee6-4cac-8bf3-bb83ceffa983)

So, it keeps in a endless looping on "failed to trigger `GC`".

**Comment by LykxSassinator** [comment]
Extra references:
1. tc-tikv-4 has plenty of `Running Tasks` in ReadPool:
![image](https://github.com/tikv/tikv/assets/18441614/05f5f04f-ed10-425e-a724-1c03ace60937)
2. reject to append raft logs:
![image](https://github.com/tikv/tikv/assets/18441614/b59d33da-7570-4953-af5f-fbf3afbdfb81)

**Comment by Lily2025** [comment]
another test with default block cache and memory-usage-limit

gc can not work when disk capacity is near full
![image](https://github.com/tikv/tikv/assets/84712107/20932f35-cdd6-4041-96e8-e042acfefe6b)

**Comment by LykxSassinator** [comment]
The above case has the same root cause in this issue.

In this case:

The memory usage in `tc-tikv-5` reached the `reject-messages-on-memory-ratio` limit, causing it reject flushing raft logs.
![image](https://github.com/tikv/tikv/assets/18441614/e192a3db-27b3-42f9-afff-e00dab0c953e)
![image](https://github.com/tikv/tikv/assets/18441614/0a499d6e-779e-4082-b424-6d8833cc907e)
![image](https://github.com/tikv/tikv/assets/18441614/dde0b32e-0f68-4dfe-8f6b-86922097f8b4)

**Comment by MyonKeminta** [comment]
For [the case posted at 20231107](https://github.com/tikv/tikv/issues/15846#issuecomment-1797971117):
 At 11/6 about 12:30, tikv-1 and tikv-3 entered disk-almost-full state. There found to be multiple issues occurring in this cluster:

* tikv-3 produces too much logs like this:
```
[2023/11/07 15:39:45.269 +08:00] [WARN] [endpoint.rs:782] [error-response] [err="Region error (will back off and retry) message: \"peer 19734 is not ready, safe_ts 445446682107445300, region 19731\" data_is_not_ready { region_id: 19731 peer_id: 19734 safe_ts: 445446682107445300 }"]
```

and this:

```
[2023/11/07 15:39:45.452 +08:00] [WARN] [endpoint.rs:782] [error-response] [err="Region error (will back off and retry) message: \"EpochNotMatch current epoch of region 36929 is conf_ver: 53 version: 184, but you sent conf_ver: 53 version: 185\" epoch_not_match { current_regions { id: 36929 end_key: 7480000000000003FF3B5F720131303030FF38363237FF300000FF0000000000F80170FF335F3233000000FCFF0419B18AF29901E2FFD200000000000000F8 region_epoch { conf_ver: 53 version: 184 } peers { id: 36930 store_id: 7 } peers { id: 36931 store_id: 6 } peers { id: 36932 store_id: 5 } } }"]
```

As the region in tikv-3 cannot apply raft logs in disk-almost-full state, it has too old region state and cannot handle requests. We may consider avoiding follower-read requests to be sent to full TiKV nodes.

* tikv-1 and tikv-3's being full made tikv-5's memory usage by raftstore significantly increased and it starts to reject appending new raft logs, which may make some write operations fail. Detail mentioned in [the comment above](https://github.com/tikv/tikv/issues/15846#issuecomment-1797988027).
* TiDB produces too much logs like:
```
[2023/11/06 18:06:57.152 +08:00] [WARN] [region_request.go:630] ["unable to find stores with given labels"] [region=36253] [leader-epoch-stale=false] [leader-unreachable=false] [leader-invalid=false] [stale-read=true] [labels="[{\"key\":\"zone\",\"value\":\"zone2\"}]"]
```
Note that the TiKV nodes labeled `zone2` are tikv-1 and tikv-3, which is exactly the full nodes.
Perhaps this can also be avoided by avoiding sending follower read requests to full nodes.

* A few transactions run for too long (over 1h). The reason is not sure yet, but possibly related to that tikv-5 cannot handle some writes. This is *one of* the reasons that GC is being blocked.
* When GC failed to run, the latest GC-ed safepoint seems to be still recorded. When there's something blocking GC (such as an active session) so that the next turn of GC is using the same safepoint, GCWorker may believe that it has already done GC with that safepoint and skip the next GC. This is not yet confirmed according to the code. If this is true, it can also be improved.

**Comment by Lily2025** [comment]
drop db failed if disk full
![image](https://github.com/tikv/tikv/assets/84712107/6e1b8e16-ddf2-47ba-a0fb-1714b933234e)

**Comment by tonyxuqqi** [comment]
@Lily2025 It's by design. When disk is full, tikv will not process write command.
