### ISSUE TITLE
TiKV OOM during CDC initial scan

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#16035]
### What version of TiKV are you using?
/ # /tikv-server -V
TiKV
Release Version:   6.5.3
Edition:           Enterprise
Git Commit Hash:   5165943fbffce298b61698a59620f415df239420
Git Commit Branch: heads/refs/tags/v6.5.3-20231116-5165943

### What operating system and CPU are you using?
K8S

### Steps to reproduce
1. TiDB cluster with 6 TiKV (16c 40g), 2 TiCDC 
2. Create cdc changefeed and pause it
3. Run workload to generate 1TB data for CDC to sync.
4. Resume cdc changefeed

### What did you expect?
TiKV should not OOM

### What did happened?
TiKV OOM

![image](https://github.com/tikv/tikv/assets/7403864/d3d9511d-f0a2-434e-9051-87f5fc4d9b44)
![image](https://github.com/tikv/tikv/assets/7403864/e082b496-cfdf-4edf-a9dc-7d245c943219)

**Comment by overvenus** [comment]
The OOM is caused by initial scan pending task surge. The size of initial scan tasks is roughly 5848 bytes, 1649639 tasks take about 8.9 GB memory.

| TiKV-2 Pending Tasks | TiKV-2 Memory |
|--------|--------|
| ![image](https://github.com/tikv/tikv/assets/2150711/40f0067b-fb3a-47ff-ad9a-ffe0228896f4) | ![image](https://github.com/tikv/tikv/assets/2150711/7cf1490f-b05d-4aef-9e72-0de90b02b8d1) | 

https://github.com/tikv/tikv/blob/5165943fbffce298b61698a59620f415df239420/components/cdc/src/endpoint.rs#L765-L780

---

To fix the issue,
* TiKV needs to limit the total number of pending tasks, it must reject requets from TiCDC when there are too many pending tasks.
* TiCDC need to limit concurrent requests, maybe revert https://github.com/pingcap/tiflow/pull/8860 (which essentially reverts the  effort of https://github.com/pingcap/tiflow/pull/3118 and https://github.com/pingcap/tiflow/pull/853 and results in tikv overload)

**Comment by hicqu** [comment]
On TiCDC instances, there are lots of such logs:
```
[2023/11/19 16:11:13.208 +08:00] [INFO] [client.go:981] ["stream to store closed"] [namespace=default] [changefeed=test1] [addr=tc-tikv-2.tc-tikv-peer.webank-cdc-tps-4590005-1-42.svc:20160] [storeID=8]
```
After a gRPC stream is re-established, all subscribed regions will be re-sent to TiKV instances. That's why there are only 50K subscribed regions on a TiKV but 15000K pending region tasks.

Limiting the total number of pending tasks is a good idea. However we still need to resolve the stream-recreation case.

**Comment by hicqu** [comment]
@overvenus https://github.com/pingcap/tiflow/pull/8860 is expected to reduce changefeed initialization time, and it does works. So I suggest to just limit total number of pending tasks on TiKVs.
