### ISSUE TITLE
qps recover after 13mins when inject one of tikv io hang

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#16368]
### What version of TiKV are you using?
v6.5.7
git hash：5f1ac992c5f4515ec493634795f1af7a726c1ec9

### What operating system and CPU are you using?
8c/32g

deploy with 6 tikv + 3 pd + 2 tidb

### Steps to reproduce
1、run tpcc 
![image](https://github.com/tikv/tikv/assets/84712107/c3b3821c-5b2b-4b9a-b6ac-fadce9db5a91)

2、inject one of tikv io hang last for 20mins
![image](https://github.com/tikv/tikv/assets/84712107/72f25574-f307-4620-a266-f8b077aac78d)

### What did you expect?
qps can recover within 5mins after inject one of tikv io hang

### What did happened?
qps recover after 13mins when inject one of tikv io hang

![img_v3_026u_3d4bb9f4-51dc-497a-8ba6-527ad26aaa2g](https://github.com/tikv/tikv/assets/84712107/ab3e3484-5ce5-447f-939e-93e07d882f64)

clinic：https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7317786419213168837?from=1703858383&to=1703862621

**Comment by LykxSassinator** [comment]
The root cause of this issue is that the peers enter into PreChaos state and ignore the WakeUp messages triggered by PD, making the duration of re-voting longer than expected.
And it's triggered as follows: 
1. Firstly, as the Hiberate Region feature is enabled, peers enter GroupState::Idle as expected.
2. Secondly, this cluster gets IO hang errors. The QPS is dropped to nearly ZERO (no new WRITE / READ flows to each TiKV node). And it triggers awaken hibernated regions mechanism by sending WakeUp messages to these peers to make them revoting into a short term.
3. However, the on_check_peer_stale_state_tick (tick period is 5 minutes by default) goes just right before the raftstore handling the WakUp messages, and it makes the state into PreChaos state.
4. Then, the WakeUp messages are ignored as the prerequisite self.fsm.hibernate_state.group_state() == GroupState::Idle is invalid.
5. Finally, these peers keep wait for another on_check_peer_stale_state_tick to make PreChaos into Chaos to trigger the re-voting progress. And this makes the recovery duration longer than expected.
