### ISSUE TITLE
TiKV min resolved ts lag up to 30s during tikv rolling restart, resulting in cdc lag increase

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#16698]
### What version of TiKV are you using?
8.0.0-alpha, 1c7b34419feaf8901046df335d4da55ad3ca9b5d

### What operating system and CPU are you using?
X86, K8S

### Steps to reproduce
1. TiDB cluster with titan on,  cluster with 30 TiKV nodes, cluster size: 70TB, througtput ~40MB/s
2. 3 CDC changefeed running to sync 4000 tables.
3. Rolling restart TiKV

### What did you expect?
CDC lag should be < 10s

### What did happened?
TiKV min resolved ts lag up to 30s during tikv rolling restart, resulting in cdc lag increase to ~30s as well.

![image](https://github.com/tikv/tikv/assets/7403864/b94ca873-f90d-4c22-ba90-ecca0fe94ee4)
![image](https://github.com/tikv/tikv/assets/7403864/4108bc29-3a1f-43c9-914d-88d1e542bec6)

**Comment by fubinzh** [comment]
cluster tikv configuration:
```
       [cdc]
        min-ts-interval = "100ms"

      [coprocessor]
        region-max-keys = 6400000
        region-max-size = "640MiB"
        region-split-keys = 5120000
        region-split-size = "512MiB"

      [gc]
        enable-compaction-filter = false

      [import]
        num-threads = 18

      [quota]
        foreground-write-bandwidth = "40MB"
        max-delay-duration = "1s"

      [raft-engine]
        dir = "/var/lib/raft/raft-engine"
        enable = true

      [raftdb]
        max-open-files = 10240
        wal-dir = "/var/lib/wal/raftdb"

      [raftstore]
        max-leader-missing-duration = "20m"
        raftdb-path = "/var/lib/raft/raftdb"
        region-compact-tombstones-percent = 10
        store-io-pool-size = 2

      [readpool]
        [readpool.unified]
          max-tasks-per-worker = 20000
          max-thread-count = 80

      [resolved-ts]
        advance-ts-interval = "1s"

      [rocksdb]
        max-open-files = 10240
        wal-dir = "/var/lib/wal/rocksdb"
        [rocksdb.defaultcf]
          level0-stop-writes-trigger = 50
          [rocksdb.defaultcf.titan]
            blob-cache-size = "24GB"
            discardable-ratio = 0.4
            min-blob-size = "4KB"
        [rocksdb.titan]
          enabled = true
[server]
        grpc-concurrent-stream = 65535

      [storage]
        reserve-space = "300GB"
        scheduler-worker-pool-size = 16
        [storage.block-cache]
          capacity = "12GB"
          num-shard-bits = 4
        [storage.flow-control]
          l0-files-threshold = 45
        [storage.io-rate-limit]
          max-bytes-per-sec = "700MB"

```

**Comment by zhangjinpeng87** [comment]
From the "scan task" metrics, I think the lag has something to do with CDC's incremental scan after leaders transfer to other TiKV nodes.

**Comment by cfzjywxk** [comment]
One of the reason causing the resolved-ts lag is the regression [issue](https://github.com/pingcap/tidb/issues/53222) in kv-client.

**Comment by MyonKeminta** [comment]
The issue may be caused by the three problems:

* https://github.com/pingcap/tidb/issues/53222 : A regression introduced by https://github.com/tikv/client-go/pull/1098 . A fix is given in https://github.com/tikv/client-go/pull/1339 , but it only works when `MaxConcurrencyRequestLimit` is not enabled.
* When a TiKV node is gracefully shutdown after evicting leader, there can still be some regions not updated in the region cache, and when the TiDB tries to send request to the region, it might still try to send to the offline TiKV first, and then takes some time to realize that the connection cannot be established.
* During restarting, the duration of check_leader (performed in resolved-ts module) can take a long time (as long as the configured timeout) trying to access the stopped TiKV node. This PR (https://github.com/tikv/tikv/pull/16943) is an optimization  that uses the `advance-ts-interval` configuration to limit the timeout, but it didin't cover all entrances of  check_leader (CDC and log-backup). In the test, CDC is used and `advance-ts-interval` is set to 1s, but when check_leader is called in CDC, it still uses the default timeout which is 5s. After a patch that passes `advance-ts-interval` to CDC module and uses it as the timeout of check_leader, the lagging mentioned in this issue is significantly reduced. This problem is recorded in issue: https://github.com/tikv/tikv/issues/17107

**Comment by fubinzh** [comment]
Verified this issue with v8.2.0 clustser, CDC lag is below 10s during TiKV rolling restart.

Cluster Details:
- Cluster size: 24TB+
- TiKV 16c64g * 12, total regions: 100k
![image](https://github.com/user-attachments/assets/f315c2a5-3ffd-435c-bf8c-9f4413f224f8)

- Cluster with 5 schemas and 5.2K+ tables, table details as below.
![image](https://github.com/user-attachments/assets/286f52db-e8b1-427d-ba82-b0928e958163)
- There are 14 changfeeds (kafka simple protocol) created for the 5.2k tables.
    - for the 5k, 100k, 500k, 2m schemas, each schema is synced by one changefeed. i.e. 4 changefeed in total, each replicating 1000, 250, 10 2 tables respectively.
    - for  the 1k schemas ( 4000 tables), 10 changefeed created, and each changefeed replicating 400 tables.
- Workload: throughtput ranges from ~40MB/s to ~80MB/s for different testings.
![image](https://github.com/user-attachments/assets/5e5b200a-069c-4ecd-87a6-a8f9fa69a95e)


![image](https://github.com/user-attachments/assets/4bbc99e4-40cd-4f89-9a08-f6f0c4d324ba)
![image](https://github.com/user-attachments/assets/58c048d5-6008-47b8-98ac-342350baf604)

![image](https://github.com/user-attachments/assets/9e929852-3933-4eb8-82d8-49e842be8bfb)
![image](https://github.com/user-attachments/assets/7873c355-4ee9-419c-bee8-3d29d138987d)


```
[root@upstream-ticdc-0 /]# /cdc version
Release Version: v8.2.0
Git Commit Hash: 498e3d3fd1cda4817e70ea50d27dcb157956349d
Git Branch: HEAD
UTC Build Time: 2024-07-03 02:52:36
Go Version: go version go1.21.10 linux/amd64
Failpoint Build: false

[root@upstream-tikv-0 /]# /tikv-server -V
TiKV 
Release Version:   8.2.0
Edition:           Community
Git Commit Hash:   6e50b27980d7d2795c2d662c7a11d03d81d4b64d
Git Commit Branch: HEAD
UTC Build Time:    2024-07-09 08:09:03
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
```
