### ISSUE TITLE
upstream and downstream data are inconsistent after running some fault test and then pitr restore and checksum

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#16809]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.1.0-alpha
Edition:           Community
Git Commit Hash:   d5e1ce68bb7d7782d54276dbba3a7966072e1a5d
Git Commit Branch: heads/refs/tags/v8.1.0-alpha
UTC Build Time:    2024-04-09 11:37:34
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
2024-04-11T12:13:36.939+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、br restore data to upstream and downstream 
2、start pitr
3、run sysbench
4、run some chaos，such as pd fault、tikv fault、tidb fault、s3 fault
6、br log restore
5、compare data consistency between upstream and downstream

### What did you expect?
the upstream and downstream data are consistent

### What did happened?
the upstream and downstream data are inconsistent

sync diff logs：
[summary.txt](https://github.com/tikv/tikv/files/14944835/summary.txt)
[sync_diff.tar.gz](https://github.com/tikv/tikv/files/14944870/sync_diff.tar.gz)

**Comment by YuJuncen** [comment]
This is because we have two concurrent procedures:
- one for advancing the progress (resolved ts, or watermark), this is a daemon and it periodically fetch ts from PD.
- one for pushing the files to the downstream.

Once we are going to "flush" a batch of backup to the external storage, **the background progress may concurrently advance the progress, with data not in the batch of flush.** Hence we advanced the watermark not properly. 

In normal cases, this won't hurt much. They will be sent to the external storage in next flush. But if:
- TiKV restarts.
- The TiKV restarted is who defined the current global checkpoint ts. (i.e. where the region with lowest checkpoint ts is.)

The data used to calculate the progress but not yet flushed will be lost.

**Comment by YuJuncen** [comment]
We should "freeze" the progress firstly when we are about to do flush. That is, we will change the `CheckpointManager` with:

- All normal `resolve` will update the `resolved_ts`(progress not yet frozen).
- When we are going to flush, call a new API `freeze` after we fetch the `min_ts`(before requeue the `min_ts`). This API will move the current `resolved_ts` to `checkpoint_ts`(the frozen progress).
- When flush done, we can "merge" the result with the frozen progress.
