### ISSUE TITLE
In-memory Engine: do not load regions that contain raw kv data

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#17628]
## Development Task

The raw kv API format is incompatible with IME, so IME should never load regions containing raw kv data.

**Comment by glorv** [comment]
Because raw kv and txn shares the same valid key range, so it's almost impossible to add pure pre-check from the configuration. In this case, we may put this restriction that use should not enable in-memory-engine in raw kv usage.

BTW, from tikv v6.1.0, TiKV introduces api-v2 for raw-kv to support mvcc and ttl. And we have pre-check for api-v2 to ensure it is not used with in-memory-engine.
