### ISSUE TITLE
pitr lag is more and more after injection pd leader io delay even if the fault was recovered

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#17889]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.5.0-alpha
Edition:           Community
Git Commit Hash:   3bd8c24d1a1eb277877557b35d3b175330e7010e
Git Commit Branch: HEAD
UTC Build Time:    2024-11-20 10:00:25
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
2024-11-22T03:48:28.037+0800

./br -V
 Release Version: v8.5.0-alpha-181-gc068b397c0
Git Commit Hash: c068b397c009506aab94ac20a9e6042f0144dffc
Git Branch: HEAD
Go Version: go1.23.3
UTC Build Time: 2024-11-20 20:48:28
Race Enabled: false

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run pitr
2、run tpcc
3、 injection pd leader io delay 500ms last for 10mins

### What did you expect?
the lag can recover after fault was recovered

### What did happened?
pitr lag is more and more after injection pd leader io delay even if the fault was recovered

![img_v3_02gv_c7555e60-7adb-4661-885e-04ba31edbd1g](https://github.com/user-attachments/assets/58e47ebd-a364-464a-9432-0449f6208483)

**Comment by 3pointer** [comment]
This is the by design behavior.

The root cause is that TiKV-1 cannot request to PD leader for 8 minutes. and the leader transfer or something like happened. make backup-stream retry observe the region. 

The total retry of observe region is 5m45s(consider out RPO promise is 5min)
![3c7ab42e-d899-45e2-a32a-005aa32d0559](https://github.com/user-attachments/assets/5109715d-ef94-43e3-a0a9-8eeecac43a7e)

If you think the total retry time is not enough, you want talk more about the retry time. feel free to reopen this issue.
