### ISSUE TITLE
Unable to join Slack chat

### ISSUE THREAD

**Issue by kmott** [tikv/tikv#17910]
## Question

In various places (website, docs, GitHub, etc), there are references to joining Slack for getting help, but unless I have an `@pingcap.com` email address, I cannot join.  If we have general questions or need help, should we just post here?

- https://tikv.org/community/community/
- https://join.slack.com/t/tikv-wg/shared_invite/enQtNTUyODE4ODU2MzI0LWVlMWMzMDkyNWE5ZjY1ODAzMWUwZGVhNGNhYTc3MzJhYWE0Y2FjYjliYzY1OWJlYTc4OWVjZWM1NDkwN2QxNDE
- https://tikv.org/chat
- https://github.com/tikv/tikv/blob/master/README.md?plain=1#L3

## Screenshot

`https://tikv.org/chat` redirects to this page:

![Image](https://github.com/user-attachments/assets/e2feb95b-cc0a-463a-b538-fa5fd6dfef84)

**Comment by zhangjinpeng87** [comment]
@kmott you can use your google account or apple account if you have.

**Comment by kmott** [comment]
> [@kmott](https://github.com/kmott) you can use your google account or apple account if you have.

Oh, I guess that means I can't signup with a non-Google/Apple email?

**Comment by HiSeren** [comment]
Hi @kmott ,thank you for bringing this to our attention, and I’m sorry for the inconvenience caused by the incorrect Slack links. The correct link to join our Slack workspace is:
[https://slack.tidb.io/invite?team=tikv-wg&channel=general](https://slack.tidb.io/invite?team=tikv-wg&channel=general)

You’re welcome to join us there for discussions or to get help! In the meantime, if you’d like to discuss a specific feature or report a bug, you’re also welcome to open a GitHub issue.

We’ve identified the outdated links in the places you mentioned (website, docs, GitHub, etc.), and we’ll update them as soon as possible to avoid further confusion.

Thanks again for pointing this out.

**Comment by kmott** [comment]
Awesome, I was able to get in.  Thank you so much!!
