### ISSUE TITLE
qps continued to drop to bottom during one of tikv io hang

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#17939]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.5.0
Edition:           Community
Git Commit Hash:   eb664852e123de68d450bc30e38419f688c5ee8b
Git Commit Branch: HEAD
UTC Build Time:    2024-11-28 09:40:17
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
2024-12-04T18:43:02.191+0800	

### What operating system and CPU are you using?
- 6-tikv-32c/128g-m6g.8xlarge (io2-8000)

### Steps to reproduce
  1、aws op env
     - 3-tidb-32c/64g-c6g.8xlarge (gp3)
     - 6-tikv-32c/128g-m6g.8xlarge (io2-8000)
     - 1-pd-32c/64g-c6g.8xlarge (gp3)
     -  Cross-3 AZ
 2、run wetech walletCenter workload
  --db-driver=mysql --mysql-db=wetech_wallet --mysql-port=4000 --mysql-user=root --threads=128 --wallet_table_size=200000000 --wallet_table_partitions=800 --wallet_log_partition_size=5000000000 --wallet_log_partition_names=p1,p2,p3 --insert_update_ratio=0.1 --mysql-ignore-errors=all --report-interval=10 --time=0 wallet.lua run
3、injection one of tikv io hang lasts for 10mins

### What did you expect?
qps can recover within 5mins

### What did happened?
qps continued to drop to bottom during one of tikv io hang which lasts for 10mins until fault recover
![Image](https://github.com/user-attachments/assets/f14c81db-a21c-4fb5-87a0-ad8b615771ac)

**Comment by LykxSassinator** [comment]
The whole event process is as follows:

1. Around 12:25:53, `pd` received the slow-score from tikv-0, marking tikv-0 as a slow node; this triggered the `evict-slow-store` scheduling;
![Image](https://github.com/user-attachments/assets/dc798e44-bbdf-45ae-950a-4c7a604e8f1d)

3. Since tikv-0's pd-worker is completely hung, it cannot process the heartbeat returned by pd; it also cannot continue to report heartbeats:
-  tikv-0 cannot respond to transfer-leader requests, with a large number of requests pending in the queue;
![Image](https://github.com/user-attachments/assets/bf2c9fb6-246f-48f1-a7a3-f77d2ef8397a)
-  At the same time, although the awaken fallback mechanism was triggered, the wake-up message might be ignored (because the lease might not have expired yet), resulting in some regions completing new leader elections, but some active regions are still waiting for transfer-leader processing.
![Image](https://github.com/user-attachments/assets/2d065de7-2077-4eb3-b9c2-a958b02b9a49)

3. A bunch of regions have to wait for the hibernate region timeout before they can re-trigger elections;

4. After tikv-0 recovers, the pending transfer-leader is processed in a large volume in a short period, but by this stage, it is already the time for leader switch back after fault recovery, and these transfer-leader will be automatically ignored (because balance-leader has already completed the scheduling).
![Image](https://github.com/user-attachments/assets/a0ecf7fd-ff67-440c-8b3c-a7bf2d7fdb0b)

**Comment by LykxSassinator** [comment]
Can be tracked as an enhancement issue for HA.

**Comment by LykxSassinator** [comment]
Supplement:

1. Why is `pd-worker` completely hung?
Ref:
https://github.com/tikv/tikv/blob/0659fcc574901dbce94b5ddf6d03d04b539f40f0/components/raftstore/src/store/worker/pd.rs#L2500-L2509

`pd-worker` is hung on trying to get the engine size, which is stuck on I/O operations.
