### ISSUE TITLE
Add more 3 tikv nodes，but the memory usage still not balance?

### ISSUE THREAD

**Issue by denghuancong** [tikv/tikv#3546]
base info
- tikv version: v2.0.4
------------------------------------

first , we use 3 nodes of tikv to store data, and we bench to test the memory usage. We found that the memory usage in one nodes is very high , other is lower . 
so, we add 3 more tikv node to the cluster ,  and we found that the hot node still the origin one and laster oom by the system . 
why we add 3 more nodes,  the memory usage still not balance ? or still not change to other ?

here is the store info from pd-ctl, 6 nodes is the same leader/region weight 
```
"leader_weight": 1,
"region_weight": 1,
```

https://github.com/pingcap/pd/issues/1226

**Comment by breeswish** [comment]
Hi, we don't schedule according to memory usage. If you meet OOM, are you setting your block cache size too large?

**Comment by denghuancong** [comment]
I think it should balance when someone scale out some tikv node into the system.
If not balance , it seem not unreasonable, we scale out tikv node because we met some tikv node using too match memory, it met oom.

**Comment by breeswish** [comment]
We don't have knowledge about per-region memory usage. It is managed by rocksdb and rocksdb don't know the region. Also, if you meet OOMs, mostly it is caused by too many cached data. Honestly schedule region away won't help, because, it will eventually cache so many data, as long as your data size > block-cache configuration > memory size .

**Comment by Hoverbear** [comment]
Seems this question is answered, but please reopen it if you need more information!
