### ISSUE TITLE
Master CI failed for a week

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3623]
## Bug Report

https://circleci.com/gh/tikv/tikv/tree/master

Failures come from Coverage test.

I guess it may be one of the cause of https://github.com/tikv/tikv/issues/3600, because master has not been successfully built for a while and cache might be invalidated.

**Comment by hicqu** [comment]
Is it a travis-ci issue? See https://github.com/travis-ci/travis-ci/issues/6253.

**Comment by breeswish** [comment]
@hicqu I guess not, we are using circle CI and from the message we can see that it failed in code coverage tests.

**Comment by breeswish** [comment]
@Connor1996 PTAL, the build starts to fail since your change (success: https://circleci.com/gh/tikv/tikv/13813, fail: https://circleci.com/gh/tikv/tikv/13837). It might not be a direct cause though.

**Comment by Connor1996** [comment]
emmm...my code changes have nothing relationship with that error, this test even doesn't reach merge logic. We didn't change `SchedTooBusy` logic for a long time, it seems that prewrite finished asynchronously everytime before call next `async_write()`. Maybe it is related to CI itself?

**Comment by Hoverbear** [comment]
@Connor1996 Have you managed to reproduce this locally?

**Comment by Connor1996** [comment]
@Hoverbear I didn't have any try to reproduce it locally, instead I make a PR https://github.com/tikv/tikv/pull/3635 to let circleci to retest. 
the result shows 
under master revert my change  **failed**
then use tarpaulin 0.6.1 instead of 0.6.3 **failed**
reset to commit(Fix CI by installing tarpaulin from git) with tarpaulin 0.6.1  **passed**
then add my change without test **passed**
then add test(not the failed test) of my change **passed**
then use tarpaulin 0.6.3 **failed**
then use tarpaulin 0.6.1 **passed**


The failed test actually may fail under some thread schedule order, seems that tarpaulin 0.6.3 makes it more easy to fail. My change commit with tarpaulin 0.6.1 passes but fails in 0.6.3. Comparing to the last passed commit(Fix CI by installing tarpaulin from git) the only difference what I can think of is the number of tests(does it matter?  tarpaulin sets `RUST_TEST_THREADS=1`). It is so weird, do you have any thought about that?

**Comment by breeswish** [comment]
Maybe you can try on a Linux machine to reproduce it faster? @Connor1996

**Comment by Hoverbear** [comment]
@Connor1996 Hmmm, okay. I haven't managed to reproduce this locally. (In fact, I cannot get Tarpaulin to even build versions 0.6.1 and 0.6.3. `cargo +nightly-2018-07-18 install cargo-tarpaulin --version 0.6.1` fails with many proc macro errors)

**Comment by breeswish** [comment]
@Hoverbear You will need to install it via the command line in our CI script :)

**Comment by Connor1996** [comment]
@breeswish `codegen-units=1` makes no effort, maybe we should rewrite the test to make it more stable?

**Comment by breeswish** [comment]
@Connor1996 Yes. codegen-units=1 only helps with performance, won't change other thing.

**Comment by Hoverbear** [comment]
Hi @Connor1996 have you made any progress here?

**Comment by Connor1996** [comment]
@Hoverbear nope, I am working on other works these days. Yesterday I tried to rewrite the test(still unstable, but I can't find a better way), it still fails.

**Comment by Connor1996** [comment]
Try to fix it in https://github.com/tikv/tikv/pull/3719. Though it is not so elegant, anyway, it works.

**Comment by Hoverbear** [comment]
@Connor1996 I am in a similar situation. :( Great work on improving the test! I wonder what changed on our CI to do this. :thinking:

**Comment by BusyJay** [comment]
Any updates on this issue?

**Comment by breeswish** [comment]
Closing, since our master are mostly green now!

https://circleci.com/gh/tikv/tikv/tree/master
