### ISSUE TITLE
Maximum blob size

### ISSUE THREAD

**Issue by gedw99** [tikv/tikv#3842]
## Question

I searched for answers for this but no luck.

I was wondering if anyone has though of using tikv for storing documents and images as blobs ?

Is this the maximum blob size ? 
https://github.com/tikv/tikv/blob/master/components/cop_datatype/src/def/mod.rs#L26

**Comment by siddontang** [comment]
Hi @gedw99 

Now it is not recommended to save blob file in TiKV because RocksDB may suffer heavy write amplification and stall. 

But this will be solved after we release our new engine Titan, which can help you save large document and image. We may release the alpha version at the middle of next month, you can have a try :-)

**Comment by gedw99** [comment]
Thank you. Will check it out.
If you have any links that is pertinent to the context feel free to respond.

**Comment by DorianZheng** [comment]
@gedw99 We have already merge our new engine `Titan` into master, it's very welcome if you wanna do some benchmark on it.

**Comment by DorianZheng** [comment]
#3985
