### ISSUE TITLE
Make get total memory cgroup-aware

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#3923]
## Feature Request

**Is your feature request related to a problem? Please describe:**
When TiKV calculating `block-cache-size`, it uses `/proc/meminfo` to get total memory. Unfortunately 
/proc/meminfo, /proc/vmstat and friends are not containerized. Meaning that they are not cgroup-aware. So for docker with limited memory resource, TiKV may set a too large block cache size and easy to OOM.

**Describe the feature you'd like:**
maybe we can check `cat /sys/fs/group/memory/memory.limit_in_bytes` to make it cgroup-aware

**Comment by tennix** [comment]
I think this is better handled during deployment, the auto provisioning tools like Ansible or Kubernetes should get the real and accurate cpu/memory easily.

**Comment by tennix** [comment]
Now I think it's better to make TiKV aware the cgroup resources itself which makes it more cloud-native. However, cgroups may reside in other directories, so we should not rely on `/sys/fs/cgroup/memory/memory.limit_in_bytes` for cgroup resources.

In Docker container, since there is usually only one process, the cgroup subsystems all reside in the root, that is `/sys/fs/cgroup`. However users can create cgroup subsystem themselves in any directory.

Instead we should follow similar approach as [automaxprocs](https://github.com/uber-go/automaxprocs/tree/master/internal/cgroups) to find the exact cgroup subsystem path, all the resource limits are configured there .

1. Parse `/proc/self/cgroup`
2. Parse `/proc/self/mountinfo`
3. Get the cgroup subsystem (cpu, memory etc) path from the above info
