### ISSUE TITLE
Compile failed on Mac

### ISSUE THREAD

**Issue by FenFenGao** [tikv/tikv#4130]
**What version of Rust are you using?**
rustc 1.32.0-nightly (14997d56a 2018-12-05)

**What operating system and CPU are you using?**
macOS 10.14.2 (18C54)
Intel Core i7

**What did you do?**
Just run ```make build```.

**What did you expect to see?**
Build successfully.

**What did you see instead?**
```
error[E0308]: mismatched types
   --> /Users/sixedge/.cargo/git/checkouts/procinfo-rs-d811f15b3a9969c8/ac3841d/src/pid/status.rs:195:1
    |
195 | named!(parse_umask<mode_t>,     delimited!(tag!("Umask:\t"),     parse_u32_octal,    line_ending));
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u16, found u32
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `procinfo`.
```

I think this submission ```* c8ff5697 util/metrics: use procinfo-rs (#3820)``` brought this error.

**Comment by zhangjinpeng1987** [comment]
@FenFenGao Have you run `make clean` first?

**Comment by siddontang** [comment]
I meet the same problem. 

PTAL @overvenus

**Comment by ice1000** [comment]
I think I'm supposed to take care of this. I'll investigate when I wake up.

**Comment by ice1000** [comment]
According to the rust documentation, https://doc.rust-lang.org/1.6.0/libc/type.mode_t.html
`mode_t` is u32. However, it's sometimes u16.

There're already someone who have encountered this issue (the size of `mode_t` is assumed to be u32, which is wrong), like rust-lang/rust#15582.

This is an easy fix.

**Comment by FenFenGao** [comment]
The type of ```mod_t``` is:
- [u16 under OSX](https://rust-lang.github.io/libc/x86_64-apple-darwin/libc/type.mode_t.html)
- [u32 under Linux](https://rust-lang.github.io/libc/x86_64-unknown-linux-gnu/libc/type.mode_t.html)

**Comment by bxeldor** [comment]
sudo make build
Password:
cargo build --features "default sse no-fail"
   Compiling procinfo v0.4.2 (https://github.com/tikv/procinfo-rs#ac3841d2)
   Compiling librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git#1317e2ed)
error[E0425]: cannot find function `parse_umask` in this scope
   --> /Users/momo/.cargo/git/checkouts/procinfo-rs-d811f15b3a9969c8/ac3841d/src/pid/status.rs:272:18
    |
272 |                | parse_umask        => { |value| status.umask       = value }
    |                  ^^^^^^^^^^^ did you mean `parse_u32s`?

   Compiling rocksdb v0.3.0 (https://github.com/pingcap/rust-rocksdb.git#1317e2ed)
error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `procinfo`.

To learn more, run the command again with --verbose.
make: *** [build] Error 101

**Comment by ice1000** [comment]
I am so sorry about this, seriously

**Comment by ice1000** [comment]
```rust
#[cfg(all(target_os = "android", target_arch = "arm"))]
named!(parse_umask<mode_t>,     delimited!(tag!("Umask:\t"),     parse_u16_octal,    line_ending));
#[cfg(not(all(target_os = "android", target_arch = "arm")))]
named!(parse_umask<mode_t>,     delimited!(tag!("Umask:\t"),     parse_u32_octal,    line_ending));
```

Sounds like not only android need `u16`. This is so confusing.

**Comment by ice1000** [comment]
tikv/procinfo-rs#6
