### ISSUE TITLE
Extract Coprocessor DAG

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4180]
## Feature Request

TiKV Coprocessor DAG is a query execution engine. Currently, it highly adheres to the storage layer and other components in TiKV. The task is to extract it into a more standalone project, to make it possible to use it in other projects outside TiKV (by providing an implementation for the KV interface it requested) as well as improving the compile speed for its benchmarks. Also, we may consider making it no_std compatible with fundamental structures and functionalities.

**Comment by YangKeao** [comment]
I am willing to work on this issue. Should I start a new repository or create a new subdir in `components` named cop_dag?

For extracting coprocessor DAG, some dependencies may need to be solved:

1. `tipb` and `kvproto`. The `builder.rs` and `handler.rs` are used to provide a convenient interface for grpc server. At the same time, a lot of types in these two crates are used in DAG. Should we depart DAG and types generated by protobuf?

2. Is `Store`, `Scanner` (and `Statistics`) already the so called "KV interface"? I think any implementation of `Store` and `Scanner` can be used directly in DAG coprocessor now.

**Comment by breeswish** [comment]
@YangKeao Thanks for your interest!

> tipb and kvproto. The builder.rs and handler.rs are used to provide a convenient interface for grpc server. At the same time, a lot of types in these two crates are used in DAG. Should we depart DAG and types generated by protobuf?

Isolate protobuf structures can be nice, but is not required. This can be a step 2.

> Is Store, Scanner (and Statistics) already the so called "KV interface"? I think any implementation of Store and Scanner can be used directly in DAG coprocessor now.

Yes. However Store and Scanner are traits from the KV interface itself. To make Coprocessor a standalone project, it should provide its own.

I think you can start from an easy path:
1. Try to extract everything in Coprocessor into a workspace.
2. Try to provide its own traits.
3. Try to provide interface without protobuf structures.

Let me know if you need help :)

**Comment by YangKeao** [comment]
It depends heavily on codec mod (in coprocessor). Should I extract it first?

**Comment by breeswish** [comment]
@YangKeao My suggestion is that, you may first extract the whole Coprocessor (including DAG part and Analyze part) into a standalone component. Then, further extract the DAG part (including the codec). Finally, optionally, you may extract the codec and the data type.

**Comment by z572505258** [comment]
The current coprocessor is for tidb. Is it possible to provide a plugin interface? then we can write custom coprocessor plugins which can process our own defined data format (such as bson).

**Comment by YangKeao** [comment]
@breeswish I don't know what `cop_datatype` is designed for. Could I place `RequestHandler` trait in it?

**Comment by YangKeao** [comment]
@breeswish I am extracting `Store` and `Scanner` trait. How should I design a new `Error` for them? (because previous errors strongly depend on storage)

The Error (and Result) with these trait shouldn't depend on the implementation of them, so I think Mvcc (from  `crate::storage::mvcc::Error`) and Engine (from `crate::storage::kv::Error`) errors shouldn't be here.

I cannot use a generic type to allow any Error type. Because `FixtureStore` should be implemented in extracted project (as `BatchIndexScanExecutor` and `BatchTableScanExecutor` depend on it).

**Comment by breeswish** [comment]
@Yangkeao I think what you need is a new Store / and a new Scanner trait, under Coprocessor's module.

**Comment by YangKeao** [comment]
As @z572505258 has said, and Yiqing Xiong in slack said he want to develop a graph database on TiKV. Should we provide some way to "register" new coprocessor ?

A new coprocessor should provide its RequestHandler and REQ_TYPE_ID, and "register" it on TiKV. Here are some questions on implementation:

1. How can I map an ID to a type?
2. Can developer "register" a coprocessor without modifying codes of TiKV? (register coprocessor runtime)

It's interesting! I'm willing to continue on providing this feature ( if it's needed).

**Comment by breeswish** [comment]
@BusyJay PTAL

**Comment by BusyJay** [comment]
Yes. Coprocessor is designed to be plug-able. However it's still all maintained inside TiKV project. It was planned to use plugin mechanism to support dynamically load user defined coprocessors, but seems no one has time to do so (and it's not urgent).

It's appreciated that you want to work on this feature. Since it's not a small change and easily lead to debate on how the interfaces and loading procedure look like, can you send an rfc to github.com/tikv/rfcs first? So that we can all discuss about it and reach an agreement.

**Comment by breeswish** [comment]
Resolved by #5155.
