### ISSUE TITLE
Abstract storage engine API

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4184]
We want to support more engines. e.g, for better scan performance, we can use a
B+-tree engine like WireTiger, or LMDB.

This issue is to track progress on abstracting TiKV over generic storage
engines.

The [`engine_traits` crate docs][engine_traits] describe the design and
migration process.

**Comment by brson** [comment]
@siddontang for a new contributor to get started on this I think we need to provide a few next steps.

To me, not knowing much about the engine, I would think the first step is to centralize all calls to the rocksdb crate into one place within tikv, so the entire engine API surface is known.

I _think_ the place those calls should be directed to is `tikv::storage::engine` which reexports everything needed from `tikv::storage::engine::rocksdb_engine`. Thus, the next steps would be:

- Identify all paths in the tikv crate that resolve to the `rocksdb` crate, and modify them to resolve to `tikv::storage::engine`. Test with `cargo check --lib` in order to just build the tikv library, and not any of the binaries, tests, etc. This will create tons of errors that need to be fixed.

- Reexport all the now-unresolved types from `tikv::storage::engine::rocksdb_engine`. Then reexport _those_ reexports from `tikv::storage::engine`, following the existing pattern of reexporting in that module. At this point `cargo check --lib` should succeed.

- Verify there are no remaining calls into the rocksdb crate by renaming the crate in `Cargo.toml`, like `rocksdb2 = { project = "rocksdb", version = "whatever" }`, and removing any `extern crate rocksdb` statements. There should be no errors outside of the `rocksdb_engine` module, and those should be resolvable with a simple `use rocksdb2 as rocksdb`.

- As with the `tikv` crate, change all the other projects, tests, benchmarks, etc to resolve into `tikv` instead of `rocksdb`. Remove the `rocksdb` dependencies from the projects in the `components` directory. Verify them in the same way as with the `tikv` library by renaming the `rocksdb` crate in `Cargo.toml`.

@siddontang does that sound right to you? Who else on the team would have opinions about the engine abstraction? Maybe @huachaohuang?

**Comment by huachaohuang** [comment]
@brson the steps you mentioned above to implement the abstraction is great. But before that, we need to design the engine API first. We need to think about what TiKV really needs instead of what TiKV currently uses. This requires a deep understanding of the current state of TiKV.

I suggest the following steps:

- Collect the requirements about the storage engine in TiKV. Check all the places related to RocksDB, and categorized them according to their functionalities.
- Design the engine API. The goal is to abstract a set of common but flexible interfaces so that:
  1. Current features from RocksDB can be mapped into these interfaces without performance compromise.
  2. Other storage engines can be adapted easily.
- Prototype the draft engine API to verify that it satisfies the requirements.
- Take the steps @brson suggested and land the abstract engine API in TiKV.

**Comment by brson** [comment]
Thanks for the detail @huachaohuang!

I do disagree about the sequencing though. No matter what the ultimate design, introducing the abstraction will be easier if the entire existing API is in one place. Having it in one place will also make it easier to think about the engine API in full.

I also suspect that a lot of upfront design here before diving into refactoring work is not going to be too helpful, that it's more productive to start prototyping, see what the problems are in abstracting the existing API, then regroup. And I think it further makes sense to land _some_ abstraction layer regardless of the design. Then with the abstraction complete, and all that experience in hand, look at what already exists, think about a better design, then refactor the existing abstraction into the desired abstraction.

Though I probably won't be doing this work, so I wouldn't insist on any particular approach.

**Comment by huachaohuang** [comment]
@brson I agree with you, it will not be a straight forward path to design and implement the engine API. Just keep the design goals in mind and go with the flow, then it will be fine.

**Comment by brson** [comment]
Thanks @huachaohuang. I went ahead of posted a self-contained issue just for refactoring all the rocksdb imports: https://github.com/tikv/tikv/issues/4229. That's a good step for a contributor.

**Comment by seansu4you87** [comment]
Hi! I'd be interested in tackling this, I took a first pass at https://github.com/tikv/tikv/issues/4229, and if that goes well, maybe I can take this on?

**Comment by aknuds1** [comment]
What's the status on this issue? I might like to try my hand at it, but I'm completely new to TiKV and don't really know where to start :)

**Comment by brson** [comment]
My latest work is https://github.com/tikv/tikv/pull/5901.

I've documented what I've learned so far in the crate docs for engine_traits: https://github.com/brson/tikv/blob/engine-traits-snapshot/components/engine_traits/src/lib.rs

My next steps are:

- brainstorm useful angles to attack next
- write a call for participation
- hack on migrating Peekable to engine_rocks

**Comment by huachaohuang** [comment]
Wow, I'm looking forward to this work. If it goes well, I may write a new storage engine for it :)

**Comment by brson** [comment]
My latest work is https://github.com/tikv/tikv/pull/5901.

I've documented what I've learned so far in the crate docs for engine_traits: https://github.com/brson/tikv/blob/engine-traits-snapshot/components/engine_traits/src/lib.rs

My next steps are:

- brainstorm useful angles to attack next
- write a call for participation
- hack on migrating Peekable to engine_rocks

**Comment by brson** [comment]
I've updated the OP with a detailed task list that people can claim and work on. I've also posted a status report here:

https://forum.tikv.org/t/engine-abstraction-status-report-and-how-to-help/76

It includes various things I've learned about this refactoring process.

**Comment by brson** [comment]
Closing in favor of https://github.com/tikv/tikv/issues/6402.
