### ISSUE TITLE
jeprof not showing heap for rocksdb

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#4260]
## Bug Report

**What did you do?**
We did jeprof heap profiling with tikv-importer (using `kill -usr2 PID`) and we find the resulting heap profile doesn't include any hint of rocksdb memory allocation. This makes jeprof not useful for finding out rocksdb memory usage. It also raise a more concerning question: whether tikv rocksdb is really using jemalloc at all.

**What did you expect to see?**
Heap profile include rocksdb memory allocations.

**What did you see instead?**
The heap profile doesn't include rocksdb allocation. Grafana is showing 15G-ish memory usage for the application (tikv-importer) while the heap profile only showing several MB of allocations. 
[heap.pdf](https://github.com/tikv/tikv/files/2896067/heap.pdf)

**Comment by brson** [comment]
I disappointingly haven't been able to manually trace through rocksdb down to the point where it calls malloc, though there are plenty of places in the code calling `free` with comments about "this value better have been allocated with malloc".

I do see though that rocksdb decides on its own at build time whether to use jemalloc, based on whether the jemalloc / tcmalloc dylibs are present. That's something that could impact results and reproducibility, though I doubt that's what's happening here.

Oh, @yiwu-arbug are you doing this testing on macos? Because on macos tikv's jemalloc is not configured to override the malloc/free symbols. _On the other hand_ jemalloc by default is supposed to override the macos "zone allocator", which I think means it overrides the system allocator at a lower level than the malloc symbols.

**Comment by yiwu-arbug** [comment]
More often rocksdb use c++ `new`/`delete` operator, which implicitly call `malloc`/`free`.

I want to confirm our tikv build indeed enable jemalloc for rocksdb. I'll investigate further.

What does it mean by "macro tikv"? @lonng may have more info on how he build the tikv-importer, but I think it is just a normal build.

**Comment by kennytm** [comment]
Not "macro TiKV", but "macOS TiKV" 🙃 

Anyway our testing is done on CentOS 7, no macOS is involved 🙂

**Comment by BusyJay** [comment]
jemalloc will replace the `malloc`/`free` calls only when it's built without prefix configuration (--with-jemalloc-prefix), which is configured explicitly on several platforms, which include macOS and musl. Prefix is disabled on standard Linux with glibc enabled.

For more information see gnzlbg/jemallocator#39 and related PRs.

**Comment by brson** [comment]
@BusyJay tikv [turns on](https://github.com/tikv/tikv/blob/master/components/tikv_alloc/Cargo.toml#L27) the `unprefixed_malloc_on_supported_platforms`, which, on current jemallocator, [looks to unprefix malloc](https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/build.rs#L45) on most platforms, but not darwin nor musl, because those have bugs when unprefixed. Tikv also disables jemalloc on windows, just due to lack of testing.

As I mentioned though, on macOS, failing to override the malloc symbols should still use jemalloc for the "zone allocator", which backs system malloc.

I believe the jemallocator crate is configured correctly to override malloc on linux and macOS.

**Comment by kennytm** [comment]
🤔 Since you mentioned `jemallocator`, when we collected the memory profile the `tikv-importer` was built based on the release-2.1 branch which didn't contain the 2018 edition changes. Perhaps we need to try again based on 3.0.

**Comment by BusyJay** [comment]
The builtin jemalloc is not configured and built with profile functionality. So TiKV links to jemallocator crate when trying to profile memory, which is done via feature "mem-profiling".

**Comment by kennytm** [comment]
Yes we did enable the `mem-profiling` feature when compiling (which is why we can get the memory dump). At least on 2.1 this is not propagated into RocksDB though.

**Comment by yiwu-arbug** [comment]
I'm able to dump a heap of tikv which is showing rocksdb allocations. I'm using tikv master.
[heap.pdf](https://github.com/tikv/tikv/files/2934872/heap.pdf)

Seems the issue is with MacOS or release-2.1? Closing the issue for now.
