### ISSUE TITLE
TiKV may fail to find PD cluster if all PD members are changed 

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#4319]
## Bug Report

TiKV may stop service if PD members are all changed and PD leader is the last one removed because TiKV caches PD member list and does not update unless  PD leader has changed.

```
PD1 PD2 PD3(leader)
        |
        | Remove PD1 and PD2, TiKV does not update member cache.
        |
PD3(leader) PD4 PD5 PD6
        |
        | Remove PD3, TiKV cannot find PD cluster because it still holds the old member cache.
        |
PD4 PD5 PD6(leader)
```

TiKV needs to update the PD member list periodically.

**Comment by siddontang** [comment]
How to fix it?

**Comment by nolouch** [comment]
ref https://github.com/tikv/tikv/pull/7028, but do not solve it at all.

**Comment by Yisaer** [comment]
I think the error can be fixed by following steps:

1. If the pd leader found the member changed (down or offline / up or be added), it will broadcast the change to tikv at most once.
2. If the pd member campaign the leader successfully, it will broadcast the result to tikv at most once.
3. The changing informing could be brought by the stream heartbeat response (like store heartbeat) or a new grpc interface hosted by tikv.
4. The member changing in PD could be directly referenced as the stream connection of the region syncer between PD leader and member.

@overvenus  @nolouch WDYT?

**Comment by nolouch** [comment]
LGTM

**Comment by overvenus** [comment]
> If the pd leader found the member changed (down or offline / up or be added), it will broadcast the change to tikv at most once.
> The changing informing could be brought by the stream heartbeat response (like store heartbeat) or a new grpc interface hosted by tikv.

Why not include term or index and send to tikv until PD gets a response in cause broken connection.
I'd like to know why you choose "at most once"?

----------

> As described below, only pd leader will broadcast the changing to tikv. If the informing failed, pd leader won't retry as tikv have its own periodically syncing ability.

I'm afraid TiKV can not know the new leader unless, older leader (or all PD server) broadcast, as the current implementation  only keeps connection to PD leader.

**Comment by Yisaer** [comment]
> Why not include term or index and send to tikv until PD gets a response in cause broken connection.

The idea is good, but I think it would be too complex for solving this problem as the recommending practice is to redeploy and update pd-address for the upstream applications(tikv/tidb) (which means it isn't necessary for PD itself to inform the member changing)

The reason why PD only inform the changing at most once is considered based on the #7028 since each tikv would sync the whole pd cluster info periodically.

> I'm afraid TiKV can not know the new leader unless, older leader (or all PD server) broadcast

I think `TiKV cann't know the new leader` is due to losing all the member added informing between the syncing interval as the solution I mentioned above tried to solve this.

Another reason why I try to make this implementation as simple as possible is so make other upstream applications(like tidb) use this solution easily.

**Comment by overvenus** [comment]
"At most once" sound problematic to me, the message could be lost during redeploy as connections are unstable (server restart).

I'm where is the complication 🤔.

TiDB does not care about it because it uses `pd.Client` (assume it handle reconnection in the pd package.)

**Comment by Yisaer** [comment]
What about adding an `Admin` API in TiKV to reset the pd-endpoints to enable the `deploying tools` reset the address in order to avoid `Rolling Update`? @overvenus

**Comment by overvenus** [comment]
I think the root cause is that from tikv's perspective all these changes are atomic (PD 3 steps down). So we could send cluster-info to tikv and wait for response before proceeding next PD member change.

**Comment by Yisaer** [comment]
In `tidb`, it dependeds `pdclient` to [periodicity update pd members](https://github.com/tikv/pd/blob/1c84784e5c26f938ae3d63972f152da170d32e4e/client/base_client.go#L149-L169) in order to avoid this problem, as currently the pd client in tikv also perform with the action,  In this respect I think we can close this issue as the current solution is enough. WDYK? @overvenus

**Comment by Yisaer** [comment]
> In `tidb`, it dependeds `pdclient` to [periodicity update pd members](https://github.com/tikv/pd/blob/1c84784e5c26f938ae3d63972f152da170d32e4e/client/base_client.go#L149-L169) in order to avoid this problem, as currently the pd client in tikv also perform as the same action, In this respect I think we can close this issue as the current solution is enough. WDYK? @overvenus

I will close this issue as the comment before, feel free to AT me if you have any question.
