### ISSUE TITLE
Consider substituting chrono-tz with other tz libraries

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4553]
## Feature Request

We have many opening issues, for example,

https://github.com/chronotope/chrono-tz/issues/23
https://github.com/chronotope/chrono-tz/issues/25
https://github.com/chronotope/chrono-tz/issues/27

and looks like no one is actually maintaining chrono-tz.

Considering that time processing is a very common demand, improving time processing has many benefits. We may:

- Maintain our own better chrono-tz
- Completely drop chrono + chrono-tz, using other libraries like cctz which looks more promising.

**Comment by kennytm** [comment]
Unfortunately 2 of these 3 issues are caused by `chrono` itself, not `chrono-tz`.

* chronotope/chrono-tz#23: as I've written in the [comment](https://github.com/chronotope/chrono-tz/issues/23#issuecomment-485943119), it is due to how `and_hms_opt` was written. You could use `TimeZone::from_local_datetime` as workaround.

* chronotope/chrono-tz#25: https://github.com/kennytm/tzfile (not suitable for production use yet)

* chronotope/chrono-tz#27: `chrono::DateTime<TZ>` will need to store a reference to the time zone in order to support the [`.timezone()`](https://docs.rs/chrono/0.4.6/chrono/struct.DateTime.html#method.timezone) method. At minimum this would require storing pointer to the field (8 bytes aligned to 8 bytes), forcing the `size_of::<DateTime<TZ>>()` to be ≥24 bytes.  For instance the size of `DateTime<&tzfile::Tz>` is 32 bytes.

[cctz](https://github.com/google/cctz) is a C++-specific library, I don't think it could be easily reused in Rust.

**Comment by breeswish** [comment]
Not an issue any more, since we now have a newly implemented DateTime.
