### ISSUE TITLE
Use arena/bump allocator to avoid frequent allocation for SlowHashAggregationExecutor

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4756]
## Feature Request

In SlowHashAggregationExecutor, we allocates N + 2 vectors each time where N is the number of rows:

https://github.com/tikv/tikv/blob/c7f62e63d3e9b4388d7c131262f678cf6b02e10a/src/coprocessor/dag/batch/executors/slow_hash_aggr_executor.rs#L207

which have a very high impact on performance. By using some pre-allocate techniques like arena allocator / bump allocator, we will save the time.

**Comment by sticnarf** [comment]
I guess those allocations are unlikely to harm performance a lot. Modern allocators like jemalloc should do well in these small allocations. (However, I haven't benchmarked.)

With an arena, there still can be much trouble. Besides the problem of self-referential in the HashMap key, the `Vec` we use needs to support expansion. Expansion means freeing the previously allocated memory and allocating a bigger one. Then, we probably need a free-list to store freed memory. Does it look like we are reinventing the wheel? I doubt if we can do better than jemalloc.

What I think is the worst, we have all these problems because we are iterating by column. I know it is for cache friendliness but I think it is actually not cache-friendly instead. Because we don't know the length of each group key, we cannot store them consecutively. Typically, the L1 cache is 32KiB, meaning it has 512 cache lines, but we have 1024 rows. Then, for every column, each access to the group key means an L1 cache miss. Even if we store them consecutively, it is unlikely that we can put all of them in the L1 cache. (32 bytes each key can be the worst case. 32bytes * 1024 = 32KiB, and we usually need something more in L1...)

However, iterating by row is not that bad as people might think. Because the column number is usually small (far less than 512, L1 cache line number), we won't have a lot more unnecessary L1 cache misses comparing to iterating by column. But then, we can encode our keys consecutively. I think the total cache miss number is likely to decrease. Even if you still worry about too many allocations, it's far easier to solve this problem when iterating by row.

**Comment by breeswish** [comment]
When I cut allocations from N * 2 to N, performance simply improved about 30% 🤣

**Comment by siddontang** [comment]
@sticnarf 

do you do some experiments?

**Comment by sticnarf** [comment]
> @sticnarf
> 
> do you do some experiments?

I just tried concatenating keys by row and tested using existing benches. No obvious performance improvement or regression. Haven't perfed to see the cache miss count.

**Comment by breeswish** [comment]
@sticnarf It concatenates keys by column due to the limit of a &mut eval interface at that time :)  I guess it should have similar cache miss compared to concatenates keys by row. However, concatenates keys by row is a required implementation if we want no allocation (i.e. what this issue for).

**Comment by sticnarf** [comment]
@breeswish The limit of &mut eval interface can be overcome by decoding column ahead of time (like in stream aggregation). But this introduces two (maybe one in HashAgg) allocations per batch.

**Comment by breeswish** [comment]
@sticnarf Yes I know that there is no such limit now.

BTW in top N executor we have a similar demand as in this issue. I am going to use raw pointers everywhere I need to bypass the lifetime checker, for simplicity && performance.. Don't know whether or not it is a good idea.

**Comment by sticnarf** [comment]
@sticnarf Raw pointer is probably unavoidable. I've been trying to solve the problem using rental, but I find it more complex than using raw pointers...
Of course, the unsafe code should be reviewed a lot more carefully.

**Comment by breeswish** [comment]
@sticnarf Good to hear that Rental is more complex. Using Rental is indeed another option I considered and is going to try with and now I can totally forget about it XD

**Comment by siddontang** [comment]
@sticnarf 

can you show us the benchmark code?

**Comment by sticnarf** [comment]
@siddontang This is the change commit: https://github.com/sticnarf/tikv/commit/32da5ad460bc9dbc789f39b7dfa835f273786e56, all other logic (including allocation number) are the same.
For hash_aggr_count_1_group_by_int_col_real_col_2_groups/batch/rows=100000, it shows a regression of 5% when iterating by row:
```
# iterating by column
$ target/release/coprocessor_executors-10eb385b9884b6a2 hash_aggr_count_1_group_by_int_col_real_col_2_groups/batch/rows=100000                                           
hash_aggr_count_1_group_by_int_col_real_col_2_groups/batch/rows=100000                                                                           
                        time:   [17.168 ms 17.305 ms 17.508 ms]
Found 2 outliers among 10 measurements (20.00%)

# iterating by row
$ target/release/coprocessor_executors-10eb385b9884b6a2 hash_aggr_count_1_group_by_int_col_real_col_2_groups/batch/rows=100000                                                            
hash_aggr_count_1_group_by_int_col_real_col_2_groups/batch/rows=100000                                                                           
                        time:   [18.477 ms 18.612 ms 18.695 ms]
```

Iterating by row is slightly more cache friendly:

```
# iterating by column
 Performance counter stats for 'target/release/deps/coprocessor_executors-10eb385b9884b6a2 hash_aggr_count_1_group_by_int_col_real_col_2_groups/batch/rows=100000 --profile-time 10':

          9,823.07 msec task-clock:u              #    1.000 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
            42,698      page-faults:u             #    0.004 M/sec                  
    38,129,573,616      cycles:u                  #    3.882 GHz                      (62.47%)
   105,967,223,815      instructions:u            #    2.78  insn per cycle           (74.99%)
    17,633,096,280      branches:u                # 1795.069 M/sec                    (75.02%)
         6,859,039      branch-misses:u           #    0.04% of all branches          (75.02%)
    27,566,130,698      L1-dcache-loads:u         # 2806.263 M/sec                    (75.02%)
     1,453,288,508      L1-dcache-load-misses:u   #    5.27% of all L1-dcache hits    (75.02%)
       354,750,828      LLC-loads:u               #   36.114 M/sec                    (49.96%)
        10,635,860      LLC-load-misses:u         #    3.00% of all LL-cache hits     (49.96%)

       9.824185259 seconds time elapsed

       9.756810000 seconds user
       0.066823000 seconds sys

# iterating by row
 Performance counter stats for 'target/release/coprocessor_executors-10eb385b9884b6a2 hash_aggr_count_1_group_by_int_col_real_col_2_groups/batch/rows=100000 --profile-time 10':

          9,792.46 msec task-clock:u              #    1.000 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
            43,202      page-faults:u             #    0.004 M/sec                  
    38,276,377,417      cycles:u                  #    3.909 GHz                      (62.47%)
   107,332,374,847      instructions:u            #    2.80  insn per cycle           (74.98%)
    17,793,767,192      branches:u                # 1817.088 M/sec                    (75.00%)
         7,144,366      branch-misses:u           #    0.04% of all branches          (75.00%)
    28,280,451,211      L1-dcache-loads:u         # 2887.982 M/sec                    (75.00%)
     1,396,071,771      L1-dcache-load-misses:u   #    4.94% of all L1-dcache hits    (75.02%)
       357,387,704      LLC-loads:u               #   36.496 M/sec                    (49.99%)
         9,842,682      LLC-load-misses:u         #    2.75% of all LL-cache hits     (49.97%)

       9.793146287 seconds time elapsed

       9.732540000 seconds user
       0.060479000 seconds sys
```
