### ISSUE TITLE
Remove HashBrown dependency

### ISSUE THREAD

**Issue by nrc** [tikv/tikv#5002]
The implementation of std::HashMap is switching to HashBrown with the 1.36 release (4th July) so there is no point in using it directly (and it costs us in terms of compilation time and possibly delays in upgrading). We should remove the dep.

**Comment by psinghal20** [comment]
@nrc Should we use the FxHash algorithm with the `std::HashMap` instead of the default SipHash? I tried it with the SipHash but it resulted in failure of `test_it_works_integration` in `slow_hash_aggr_executor.rs` due to different sequence of results in each execution when checking the group by column query [here](https://github.com/tikv/tikv/blob/master/src/coprocessor/dag/batch/executors/slow_hash_aggr_executor.rs#L452).

**Comment by nrc** [comment]
We should continue to use the current hash algorithm. This should be pretty easy, you need to change the type alias in components/tikv_util/src/collections.rs to use `std::BuildHasherDefault<FxHasher>` rather than `hashbrown::hash_map::DefaultHashBuilder`. It's possible there will be a few more issues, but that should do it.
