### ISSUE TITLE
binary not found in bin directory after running make_relase or make_fail_release successfully

### ISSUE THREAD

**Issue by cwen0** [tikv/tikv#5075]
After running `make fail_release`  or `make release` successfully,  but I did't find the tikv-server binary in the bin directory.
```
$ make fail_release
FAIL_POINT=1 make release
cargo build --release --no-default-features --features " jemalloc sse"
    Finished release [optimized] target(s) in 0.29s
$ cd bin
cd: no such file or directory: bin
```  

I found that the binary was put in `target/release` directory,  and only when to run `make dist_release`, the following shell will be executed. 

```
@mkdir -p ${BIN_PATH}
	@cp -f ${CARGO_TARGET_DIR}/release/tikv-ctl ${CARGO_TARGET_DIR}/release/tikv-server ${CARGO_TARGET_DIR}/release/tikv-importer ${BIN_PATH}/
``` 

If this behavior is expected,  we should explain it in `README` or docs to prevent users from finding the binary.

**Comment by brson** [comment]
Thanks for the report @cwen0. I didn't consider the user-impact of this change.

This change is intentional, but I'm open to being told it should be reverted.

My belief has been that that `bin` directory is for the CI to use, not users or developers.

This change in behavior is clearly surprising for those using the `bin` directory, but I think it is the right change to make, as standard Rust behavior is for bins to be in the target directory, hence tikv developers should expect the bins to be in target, not a non-standard bin dir.

I should definitely have communicated this change somewhere, but it did not occur to me.  I don't see the existence of the `bin` directory documented in the README, so I don't see that in makes sense to mention the _absense_ of the bin directory in the README.

It does occur to me though that the README doesn't include instructions on how to build tikv releases, just general "building and testing" instructions, which now _do not_ build with identical settings to an official release. So any users that might want to make their own releases won't know they need to run `make dist_release`. That is definitely an omission in the docs.

Interested in other opinions.

**Comment by cwen0** [comment]
@brson Thanks for your response.

**Comment by zhouqiang-cl** [comment]
Now it has the following errors
make[1]: Entering directory `/home/jenkins/workspace/build_tikv_master/tikv'

cargo build --release --no-default-features --features " jemalloc portable sse failpoints"

   Compiling tikv v4.0.0-alpha (/home/jenkins/workspace/build_tikv_master/tikv)

error[E0308]: mismatched types

    --> src/raftstore/store/fsm/apply.rs:1588:9

     |

1587 |       ) -> Result<(AdminResponse, ApplyResult)> {

     |            ------------------------------------ expected `std::result::Result<(kvproto::protobuf::raft_cmdpb::AdminResponse, raftstore::store::fsm::apply::ApplyResult), raftstore::errors::Error>` because of return type

1588 | /         fail_point!(

1589 | |             "apply_before_split_1_3",

1590 | |             { self.id == 3 && self.region_id() == 1 },

1591 | |             |_| {}

1592 | |         );

     | |__________^ expected enum `std::result::Result`, found ()

     |

     = note: expected type `std::result::Result<(kvproto::protobuf::raft_cmdpb::AdminResponse, raftstore::store::fsm::apply::ApplyResult), raftstore::errors::Error>`

                found type `()`

     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)



error: aborting due to previous error



For more information about this error, try `rustc --explain E0308`.

error: Could not compile `tikv`.



To learn more, run the command again with --verbose.

make[1]: *** [release] Error 101

make[1]: Leaving directory `/home/jenkins/workspace/build_tikv_master/tikv'

make: *** [fail_release] Error 2

**Comment by zhouqiang-cl** [comment]
@brson PTAL again
