### ISSUE TITLE
Add a metric to observe raft log commit duration

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#5421]
For now, we have no way to observe commit duration of a raft log, #3688 try to solve this by adding an extra `CLOCK_MONOTONIC_RAW`(syscall), but it turns out too expansive. We need to find a less expansive to observe the duration.

**Comment by NingLin-P** [comment]
Maybe we can use ```poll_ctx.lease_time``` instead of  ```monotonic_raw_now()``` as the finish time of raft log commit, and the commit metric will be ```poll_ctx.lease_time - propose_time```.
```poll_ctx.lease_time``` are set when process the first proposal in the first Fsm in a Batch, and 
is use as the ```renew_lease_time``` of **all** ```ProposalMeta``` inside a Batch, and that is ok, because when process Msgs inside a Batch, there is no time comsume work like send mssages or write to disk, so the deviation is small. That is the same reasion to use ```poll_ctx.lease_time```, the time to set ```poll_ctx.lease_time``` and the time to call ```RawNode::ready_since``` is close, and bewteen them there is not time consume work, however, in #3688, bewteen ```RawNode::ready_since``` and  ```monotonic_raw_now()``` there have works both send messages and write raft log to disk which make the metric not accurate
