### ISSUE TITLE
Why should not deploy pd and tikv on the same node

### ISSUE THREAD

**Issue by mysunnyshine** [tikv/tikv#5478]
## Question

Why should not deploy pd and tikv on the same node?  bad performance or  other considerations?

**Comment by Hoverbear** [comment]
Hi!

It's generally not recommended to colocate PD and TiKV because it will lead to poor performance under high load.

PD and TiKV are both quite resource intensive, and introducing more services on a single node will increase thread contention, memory pressure, and disk pressure, resulting in much slower response times.

You can also consider the resilience of the cluster, a cluster with colocated TiKV and PD instances may be more sensitive to failure, creating latency spikes on writes during transient network partitions.
