### ISSUE TITLE
Help using CLion on Mac to debug tikv

### ISSUE THREAD

**Issue by zplinuxlover** [tikv/tikv#5572]
I setup environment on mac os using CLION ide , I compile the rust code success, but when i debug the code, I could not view the variable value. How do you debug the rust code, using vim or emacs?

**Comment by Hoverbear** [comment]
Hi @zplinuxlover ,

I've had some success using VSCode before, similar to the way described here: https://www.forrestthewoods.com/blog/how-to-debug-rust-with-visual-studio-code/

It looks like CLion's support is still preliminary: https://intellij-rust.github.io/docs/faq.html

You can see a general overview of Rust IDE capabilities here: https://areweideyet.com/

I'm closing this since it's not an issue with TiKV. :)

If you get it working it'd be great if you could leave a follow up comment for others in the future to learn how you did it!

**Comment by zplinuxlover** [comment]
My problem is that, i can use clion to view tikv code, but i compile it to debug tikv , I could not view local variable when debugging,I read the article above, but i have not known how to view the local variable when debugging

**Comment by Hoverbear** [comment]
Are you able to view them on other Rust projects?

**Comment by zplinuxlover** [comment]
yes, i can view them on my demo project

**Comment by zplinuxlover** [comment]
Can you give me some advice to help me debug tikv? I am a beginner of rust

**Comment by Hoverbear** [comment]
TiKV should be able to be debugged like any other Rust project. Can you build TiKV from the command line successfully?

**Comment by zplinuxlover** [comment]
yes, i run the command `make build` success

**Comment by Hoverbear** [comment]
I'll reopen this and we can hope someone with a Mac who uses CLion can help you. :)

**Comment by zplinuxlover** [comment]
I compile tikv on ubuntu, and i debug it by rust-gdb, but i still can not use `p var` to view the value of the var

**Comment by zplinuxlover** [comment]
I resolve the problem, thanks,
I change the Cargo.toml value of `[profile.dev] debug = true`

**Comment by Hoverbear** [comment]
Oh, amazing detective work. :) Thank you for documenting your solution!
