### ISSUE TITLE
UCP: Improve TiKV metrics performance

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5708]
## Description

In TiKV, mostly a global metrics is used. It has bad performance when there is high concurrency due to cache invalidation. What’s worse is, many of them are metric vector, which is even slower.

A solution is to use thread local storage to store a local metrics, and use the corasetime crate to periodically flush the local metrics to the global metrics. Previous experiment shows that this approach’s cost is very low.

## Score

- 1680

## Mentor(s)

- @breeswish
- @sticnarf 

## Recommended Skills

- System and concurrency programming
- Rust language

**Comment by Renkai** [comment]
@sre-bot You are in abnormal state,tell me when you recovered

**Comment by you06** [comment]
@Renkai Sorry for the accidents of bot, try picking up again.

**Comment by Renkai** [comment]
Since the file list for improvement is long,I made a todo list to show progress.
- [ ] ./components/tidb_query/src/metrics.rs
- [ ] ./components/pd_client/src/metrics.rs
- [ ] ./components/tikv_util/src/worker/metrics.rs
- [ ] ./components/tikv_util/src/future_pool/metrics.rs
- [ ] ./components/sst_importer/src/metrics.rs
- [ ] ./components/backup/src/metrics.rs
- [ ] ./src/raftstore/coprocessor/metrics.rs
- [ ] ./src/raftstore/store/fsm/metrics.rs
- [ ] ./src/raftstore/store/metrics.rs
- [ ] ./src/raftstore/store/worker/metrics.rs
- [ ] ./src/coprocessor/metrics.rs
- [ ] ./src/server/metrics.rs
- [ ] ./src/server/lock_manager/metrics.rs
- [ ] ./src/storage/metrics.rs
- [ ] ./src/storage/mvcc/metrics.rs

**Comment by you06** [comment]
@Renkai you don't need to manipulate the challenge anymore, the 1st season's game is already over.

**Comment by Renkai** [comment]
A new route to resolve this issue: remove all `with_label_values`
