### ISSUE TITLE
Support ENUM / SET / BIT in Coprocessor

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5738]
## Description

The Coprocessor does not support the ENUM / SET / BIT  type in the current implementation, which cause some expressions cannot be pushed down if the expression contains the ENUM / SET / BIT type. We can improve this situation by implementing ENUM / SET / BIT operations.

## Difficulty

- Hard

## Score

- 2100

## Mentor(s)

- @lonng
- @breeswish

## Recommended Skills

- Rust programming
- Algorithm

**Comment by TennyZhuang** [comment]
Why this is one challenge instead of three?

**Comment by breeswish** [comment]
@TennyZhuang  Since they share similar behavior.

**Comment by cireu** [comment]
I'm reading the source of TiKV and try solve this issue. But I found these consts are really confusing https://github.com/tikv/tikv/blob/00c475f3aeac5ddd478d21d88a17cc7d34adb216/components/tidb_query/src/codec/datum.rs#L23

It lacks documentation and mismatch any one of following const declaration.

- https://github.com/pingcap/tidb/blob/master/types/datum.go#L37
- https://github.com/pingcap/tipb/blob/master/proto/expression.proto#L23

Do you have some ideas on these consts?

@breeswish @lonng

**Comment by breeswish** [comment]
Hi, these flags comes from:

```golang
const (
	NilFlag          byte = 0
	bytesFlag        byte = 1
	compactBytesFlag byte = 2
	intFlag          byte = 3
	uintFlag         byte = 4
	floatFlag        byte = 5
	decimalFlag      byte = 6
	durationFlag     byte = 7
	varintFlag       byte = 8
	uvarintFlag      byte = 9
	jsonFlag         byte = 10
	maxFlag          byte = 250
)
```

in `util/codec/codec.go`.

**Comment by cireu** [comment]
The `FieldType` message from tipb missing slot `Elems` which is neccesary for us to enable push down for ENUM/SET type. This property exists in tidb parser, Can we add this property directly for tipb?

@breeswish  @lonng 

- https://github.com/pingcap/parser/blob/master/types/field_type.go#L32
- https://github.com/pingcap/tipb/blob/master/proto/expression.proto#L14

**Comment by breeswish** [comment]
Hi, @cireu It already exists in tipb's ColumnInfo.

**Comment by cireu** [comment]
Good, last week I was reading and learning the copr part of TiKV and try to
understand how to add new type support for it.

IIUC, Following step is neccesary for a new eval type.

- Implement the type itself and some basic trait, for ENUM, it's just a
  key-value pair. Refer to
  [this](https://github.com/pingcap/tidb/blob/master/types/enum.go).  And my
  naive implementation is [here](https://github.com/tikv/tikv/pull/6266/files).

- Implement decoding and encoding functionalities, these code may separate in
  different file like `raw_datum.rs` `table.rs` `chunk/column.rs`.
  And we may need to add `EnumDecoder` and `EnumEncoder` trait for ByteSlice.
  refer to [codec impl](https://github.com/pingcap/tidb/tree/master/util/codec)
  and [chunk impl](https://github.com/pingcap/tidb/tree/master/util/chunk) in
  TiDB.

- Implement conversion trait in `convert.rs`(e.g. `ToInt`, `ConvertTo`) maybe
  refer to
  [this](https://github.com/pingcap/tidb/blob/master/types/convert.go).

- Add `Enum` variant for `Datum` and covert the cases for this new variant in
  pattern match.

- Make `Enum` become an evaluable type by adding variant to `ScalarValueRef` and
  `VectorValue`. These are trivial work since we have macro to reduce such
  boilerplate.

Ok, back to the original question. I try to impl `RawDatumDecoder<Enum>` for
byte slice. But I found the [signature of function](https://github.com/tikv/tikv/blob/master/components/tidb_query/src/codec/raw_datum.rs#L260) in that trait accept a
`FieldType` but not a `ColumnInfo`. 

What' s more, both `FieldType` and `ColumnInfo` implemented `FieldTypeAccessor`,
which provides a common interface for user to access metadata. And I also found
that type `FieldType` has slot `Elems` in pingcap/parser. So I guess
`ColumnInfo` and `FieldType` is something similar.

Please correct me if I misunderstood anything, thanks a lot! @breewish

**Comment by breeswish** [comment]
Hi, @cireu 

In general there are two ways to support ENUM / SET in TiKV.

### A. Always treat ENUM / SET as string

By using this solution, you need to convert enum to string when it is retrieved from table. This requires minimal modification (since it does not introduce a new eval type).

However this solution have correctness issues. When sorting enums and casting enums to integer, their index instead of corresponding value need to be used.

### B. Introducing a new Enum evaluable type

By using this solution, you can get correct behaviour in all situations. Ideally enum variants should be part of the type (i.e. stored in FieldType). However you need to know that currently TiDB does not have an Enum eval type, which means there is no CastEnumToInt or CastEnumToString. This missing cast does not cause trouble when it is used in `Datum` since `Datum` support implicit casting, but denifitely causes trouble when it is used in (batch) vectorized execution (e.g. VectorValue, rpn_expr), since the framework does not support implicit casting.

As you have already discovered, `FieldType` in protobuf does not have `Elems`, which simply means it cannot be used to fully store everything an Enum contains. For this reason, the `FieldType` will likely to be improved in order to support the Enum.

**Comment by cireu** [comment]
> B. Introducing a new Enum evaluable type

I agree with this solution because both value and name of an enum is necessary while processing. But looks that it still has a techinal issue.

Maybe I can take a look at BIT type first.

**Comment by cireu** [comment]
Can we represent a ENUM type in a formatted string(e.g. `{value}<delim>{string}`)?

**Comment by breeswish** [comment]
We decided to implement ENUM / SET first, so that I'm going to close this issue for https://github.com/tikv/tikv/issues/8605
