### ISSUE TITLE
Failpoint tests will not run when make dev

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#6097]
When calling command `make dev` on master, only integration tests are run, but failpoints is ignored.

When I run it explicitly, it refuses to run and reports:
```
% cargo test --no-default-features --features " jemalloc portable sse failpoints protobuf-codec" -p tests --test failpoints  -- --nocapture  ""
error: target `failpoints` in package `tests` requires the features: `failpoints`
Consider enabling them by passing, e.g., `--features="failpoints"`
```

**Comment by BusyJay** [comment]
I think it's introduced by #5379.

**Comment by nrc** [comment]
I'm investigating. I can reproduce the error and it is certainly introduced by #5379, in particular by separating out the `tests` crate (which was done to work around another Cargo bug with features :-| ).

Minimal repro I'm using is `cargo test --no-default-features --features="failpoints" -p tests --test failpoints`. The issue seems to be that the feature is not passed to the failpoints test. Not sure why yet.

(Given that issue, the failpoints test being skipped when not mentioned explicitly is expected).
