### ISSUE TITLE
Avoid GC from reading unnecessary SST

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#6316]
## Description

We have a rocksdb iterator with ts filter now, see https://github.com/tikv/tikv/pull/6194. So we can leverage it for GC worker to filter out the SST whose `MVCCProperty::min_ts` > `safepoint` which may reduce the IO and CPU usage for GC.

First, you need to get the knowledge how GC works in TiKV, see https://pingcap.com/docs/stable/reference/garbage-collection/overview/

The entrance of gc logic is here https://github.com/tikv/tikv/blob/master/src/server/gc_worker/gc_worker.rs#L364. The process is divided into two steps: scan_keys and gc_keys. The two steps use [MvccReader](https://github.com/tikv/tikv/blob/master/src/storage/mvcc/reader/reader.rs#L19) to do the actual scan, 
you should set the data cursor with hint_max_ts = safe_point just like how https://github.com/tikv/tikv/pull/6291 does

test: you should adjust the case https://github.com/tikv/tikv/blob/master/src/storage/mvcc/txn.rs#L1548 to cover your change 

## Mentor(s)

- @MyonKeminta  @Connor1996 

## Recommended Skills

- Rust programming

**Comment by siddontang** [comment]
Good idea!!!

**Comment by MyonKeminta** [comment]
Good idea. I can try this after finishing Green GC, if no other contributor picks this task.

**Comment by yiwu-arbug** [comment]
@hicqu any comment about this task? Do you see correctness concern, and do you see it conflict with compaction filter GC?

**Comment by yiwu-arbug** [comment]
@govardhangdg please take a look at this task. Thanksk!

@Connor1996 please help to fill in more details, like which file need to be update, what API to use to filter SST, and how to write a unit test. Thanks.

**Comment by Connor1996** [comment]
> @govardhangdg please take a look at this task. Thanksk!
> 
> @Connor1996 please help to fill in more details, like which file need to be update, what API to use to filter SST, and how to write a unit test. Thanks.

detail is updated in the PR description

**Comment by govardhangdg** [comment]
Thanks @Connor1996

**Comment by hicqu** [comment]
Seems not conflicts with "gc with compaction filter". `scan_keys` and `gc_keys` are part of traditional GC.

**Comment by govardhangdg** [comment]
> The two steps use MvccReader to do the actual scan,
https://github.com/tikv/tikv/blob/master/src/storage/kv/cursor.rs#L490you should set the data cursor with hint_max_ts = safe_point just like how #6291 does 

I observed that in #6291 the `cursor` is created using the `CursorBuilder`. But in this case the cursor is obtained from call to `self.snapshot.iter_cf` (https://github.com/tikv/tikv/blob/master/src/storage/mvcc/reader/reader.rs#L332). This function directly returns a `Cursor` object (https://github.com/tikv/tikv/blob/6b0767b53838ad6d88b252416e26ef36924db7d1/src/storage/kv/rocksdb_engine.rs#L320).
I have thought of another way to do it. 
It is to create the `iter_opt` in https://github.com/tikv/tikv/blob/master/src/storage/mvcc/reader/reader.rs#L330 as done in https://github.com/tikv/tikv/blob/master/src/storage/kv/cursor.rs#L490. But this would require a change in API for the MvccReader::scan_keys (https://github.com/tikv/tikv/blob/master/src/storage/kv/cursor.rs#L490) because I'd have to pass in the `safe_point` to this function as I don't have any other way of accessing it here. 
So, is it okay to change the API? Or is there any other way to do this? Or have i misunderstood the problem? @Connor1996 @yiwu-arbug.
Thanks.

**Comment by Connor1996** [comment]
> the cursor is created using the CursorBuilder. But in this case the cursor is obtained from call to self.snapshot.iter_cf
maybe you can use `CursorBuilder` instead of `iter_cf()`?

> I have thought of another way to do it. It is to create the iter_opt
it looks good to me too

>  is it okay to change the API?
it's okay

**Comment by govardhangdg** [comment]
> data cursor with hint_max_ts = safe_point

Just making sure, it's `hint_max_ts` and not `hint_min_ts` right? @Connor1996

**Comment by Connor1996** [comment]
Yes
