### ISSUE TITLE
How region split works

### ISSUE THREAD

**Issue by doggeral** [tikv/tikv#6387]
## Question

Hi TiKV team,  
I'm new to TiKV and TiTB. I'd like to know how region split works and if there is any impact to serve the online traffic when the region is spliting. I went though the doc but I didn't find the answer. Could you help to share with some details?

Thanks,
Longfang

**Comment by overvenus** [comment]
Thank you for interesting in TiKV!

Region split is part of multi-raft implementation and it's a bit complex, the brief workflow:

1. Region size exceeds a threshold (default: 120MB),
2. it chooses a suitable key as the split key (usually evenly divided the region),
3. it asks PD for unique IDs for new Region and peers,
4. the split key and IDs are composed as a split command and proposed to the raft group,
5. apply the split command once it's committed. (This is the last step).

> ... and if there is any impact to serve the online traffic when the region is splitting.

Yes, it does affect a small number of requests. TiKV client retries, since Region split usually finishes within 1 second, so that caller of TiKV client won't observe errors.

**Comment by jungle-zh** [comment]
hi, overvenus ,  you said there is a step 'split command is proposed to the raft group' , does that  mean  once the split log is committed to the raft , then the split is considered to be successful, but what if apply failed .for example , a region of three peers, after leader commit the split log, the other two peer dies before applying the log, how to deal with this situation ?

**Comment by jungle-zh** [comment]
Hi, overvenus :
you said there is a step 'split command is proposed to the raft group' , does that mean once the split log is committed to the raft , then the split is considered to be successful, but what if apply failed .for example , a region of three peers, after leader commit the split log, the other two peer dies before applying the log, how to deal with this situation ?
thanks  for you reply

**Comment by overvenus** [comment]
> does that mean once the split log is committed to the raft , then the split is considered to be successful

In most cases, yes. But it could fail even if the split command is committed, e.g., split command is committed twice within one Region Epoch, the later split will fail.

> for example , a region of three peers, after leader commit the split log, the other two peer dies before applying the log, how to deal with this situation ? 

The leader should apply committed raft logs and then stop because it loses quorum.

**Comment by doggeral** [comment]
Thanks for your explanation. Will deep dive the source code to know more :)
