### ISSUE TITLE
How to recover from tikv failure

### ISSUE THREAD

**Issue by salarali** [tikv/tikv#6443]
## Question

I have 2 TiKV's and 1 PD with a replication of 1.
I lose all the data in one of the tikv, because of node failure (aws instance store). Now, how do I recover from this state? 

I have tried `pd-ctl store delete <id>`, but its still in offline state. Can I force it to be in tombstone state because I have no replicas?

When I try to restart tikv, I get this error: `duplicated store address:`

Thanks for you help.

PD Version: 
```
Release Version: v3.0.7
Git Commit Hash: 7a5909ed3bae74d0c6c728ca931f240233aca03a
Git Branch: HEAD
UTC Build Time:  2019-12-04 10:06:16
```

TiKV Version
```
TiKV Control (tikv-ctl)
Release Version:   3.0.7
Git Commit Hash:   ac6f02648a8c6ccb7ccafca20287e1b27007e4a0
Git Commit Branch: HEAD
UTC Build Time:    2019-12-04 10:06:20
Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)
```

**Comment by shafreeck** [comment]
In this case, you can use the internal API to set the state to `Tombstone` by force.

```
curl -XPOST http://your-pd-address:2379/pd/api/v1/store/1/state?state=Tombstone
```

**Comment by shafreeck** [comment]
Feel free to reopen the issue if you still have the problem.

**Comment by salarali** [comment]
So I ran this command, now when my application tries to fetch regions that resided in bad node, I get this error: `loadStore from PD failed, id: 103162`. And when I print the regions in the pd, it does show regions residing in the bad node. What should I do now to resolve the state?

**Comment by salarali** [comment]
I asked a similar question in the slack group and got this response:
`
zhangjinpeng  15 days ago
seems we don’t have such a tool to satisfy this demand( this tool need to make some empty range in  tikv for these holes). pd-recover is used to recover pd when meta data is corrupted in pd.
`


https://tikv-wg.slack.com/archives/CDDBKTQ9X/p1588234587097100

**Comment by shafreeck** [comment]
So this issue can be closed now?

**Comment by salarali** [comment]
So there is no tool existing that can help me with this scenario? I have a 10 node cluster now with replication factor of 1. So if any of the nodes somehow dies, there is no way for me to recover?

**Comment by shafreeck** [comment]
I am afraid not. Use a replication factor greater 1 if you want to achieve the HA.

According to what you said, the node you set to tombstone forcibly has no replicas, why do you want to access it later?

**Comment by salarali** [comment]
Its acceptable to me to lose the data in the bad node. There is no way to recover the cluster and continue using it because of this error: `loadStore from PD failed, id: 103162`

**Comment by shafreeck** [comment]
Do you have any related error message in the log of your application or PD?

**Comment by salarali** [comment]
In my application I got: `loadStore from PD failed, id: 103162` and `pdRPC` error. Sadly, I didn't store the entire messages.

**Comment by shafreeck** [comment]
Would you like to try running the command to remove the tombstone stores:

```
curl -XDELETE http://your-pd-address/pd/api/v1/stores/remove-tombstone
```

**Comment by salarali** [comment]
Let me try setting up a cluster.

**Comment by dveeden** [comment]
@salarali was the issue resolved?

**Comment by salarali** [comment]
I didn't try again but I think that functionality doesn't exist. If the replication factor is 1 and u lose some regions, the cluster is unable to recover. 

Maybe the new versions have improved the logic but I haven't tried them out.

**Comment by dveeden** [comment]
With a replication factor of 1 and say 2 TiKV instances your table is split in say 10 regions and each TiKV instance will hold 5 regions.

If a TiKV instance permanently dies there half of the regions for this table are gone. This is an unrecoverable situation. It might be possible to get some data out of the remaining 5 regions on the remaining TiKV node, but not the complete table.

If a TiKV instance restarts or otherwise is temporarily available this is a recoverable situation. However with a replication factor of 3 this would not have lead to downtime as new raft leaders would be elected.

With a replication factor of 2 raft election wouldn't work as a single failure would not leave >50% of the group online. However manual recovery might be possible.

In any of these situations you should make backups or have some other way to restore after an unrecoverable failure.

I would strongly suggest to use a replication factor of 3 to guard against data loss and unavailability.

Could you share some information about why you want to run a cluster with less replicas and what you expect from a recovery in these cases?

**Comment by salarali** [comment]
I would expect the cluster to recover properly with the remaining regions. Of course the 5 regions are lost, but I should be able to use the data in the remaining 5 regions. Currently, if I lose a single tikv node, basically I have to remake the entire cluster. 

Mostly price and the fact that I am okay with losing the data if the node dies.
