### ISSUE TITLE
UCP: Correct Coprocessor PerfContext

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#6973]
## Description

Now Coprocessor enables unified thread pool by default, which will break tasks into multiple pieces. However the structure `PerfStatisticsInstant` used in Coprocessor is Thread Local, and it cannot be safely sent between threads. Currently `PerfContext` is not marked as `!Send` and it causes misleading log.

Goals:

- Output correct PerfContext log in Coprocessor slow log.

## Score 

* 300

## Mentor(s)

* @breeswish 
* @sticnarf 

## Recommended Skills

* Rust programming

**Comment by TennyZhuang** [comment]
@sre-bot /pick-up-challenge

**Comment by govardhangdg** [comment]
@breeswish @sticnarf can you please tell what is meant by "misleading log"?

**Comment by breeswish** [comment]
@govardhangdg 

`PerfStatisticsInstant` utilize two `PerfContext` to generate a delta statistics. It works as follows:

```rust
let x = PerfStatisticsInstant::new();
....
let y = x.delta();
```

However, in Coprocessor `x` can now be sent across different threads, which makes `y` incorrect.

**Comment by ziyi-yan** [comment]
Hi, @breeswish, I had already investigated this issue for about two days and discussed it in tikv-wg slack #challenge-program channel with @sticnarf for a while. Maybe I should just post it here. So here is my latest update.
Due to [this change](https://github.com/tikv/tikv/pull/6250), the RequestHandler.handle_request is `async fn` now. It’s right in between the `tracker.on_begin_*()` calls and `tracker.on_finish_*()` calls. https://github.com/tikv/tikv/blob/778635c5109cf1090961aad567592c6330c69e47/src/coprocessor/endpoint.rs#L369-L382
So the beginning and finish of a tracker could be split into different threads when executed on the yatp thread pool, which might get different `PerfContext`s and lead to wrong `delta()` calculation.
I might be a problem but I think the [typical usage of PerfContext](https://github.com/facebook/rocksdb/wiki/Perf-Context-and-IO-Stats-Context#how-to-use-them) is in one-thread cases (maybe that's why `PerfContext` is thread-local). Now we use yapt to run one coprocessor task across different threads, I am wondering whether it is still reasonable to use `PerfContext`.
A possible solution might be using some configuration to inject statistics-related code into yapt because the thread is managed by it.
Please let me know if you have any thoughts or better solutions. Thanks!

**Comment by breeswish** [comment]
@ziyi-yan Your studying is correct. However `PerfContext` is the only way to obtain some RocksDB statistics that we need (e.g. how many internal skipped keys), so that I don't think it is possible to avoid its usage. A (hacking) solution could be recording the delta before switching to another thread.

**Comment by ziyi-yan** [comment]
Thanks for your advice! I am going to do some further study in async and future to figure out whether we can intercept all those switch points.

**Comment by ziyi-yan** [comment]
I just finished the first draft about the solution recoding the delta before switching. I wrapped the `handler.handler_request()` future and push tracker inside the `poll()` to make sure each delta calculation is in the same thread. There are some codes like storage statistics still left outside of the track future, but I want to publish it first to get some feedback. Is it the right direction? Thanks!

**Comment by ladrift** [comment]
@yiwu-arbug Hi! Per the discussion above, [this PR](https://github.com/tikv/rust-rocksdb/pull/442) doesn't really solve the "misleading log" issue. Here is [my work](https://github.com/tikv/tikv/pull/6999). I hope we can re-open the issue and give me the opportunity to finally get the UCP scores. Thanks!

**Comment by ziyi-yan** [comment]
@yiwu-arbug Hi! Per the discussion above, [this PR](https://github.com/tikv/rust-rocksdb/pull/442) doesn't really solve the "misleading log" issue. Here is [my work](https://github.com/tikv/tikv/pull/6999). I hope we can re-open the issue and give me the opportunity to finally get the UCP scores. Thanks!

**Comment by sticnarf** [comment]
I've fixed the issue description. RocksDB's `PerfContext` is already `!Send`. The actual problem is that `PerfStatisticsInstant` should not be `Send`.

**Comment by ziyi-yan** [comment]
Thanks, @sticnarf! I use the interceptor pattern recommended by you to implement [this PR](#6999) to prevent calculating delta between `PerfContext`s in different threads and hope it can fix the "misleading log" problem. So, maybe we should not mark `PerfStatisticsInstant` as `!Send`, because doing that will prevent the future being passed to thread pool.
Here is the error log when I `impl !Send for PerfStatisticsInstant {}`:
```
error: future cannot be sent between threads safely
   --> src/coprocessor/endpoint.rs:412:14
    |
412 |             .spawn_handle(
    |              ^^^^^^^^^^^^ future returned by `handle_unary_request_impl` is not `Send`
    |
```

**Comment by sticnarf** [comment]
@ziyi-yan Right. Making `PerfStatisticsInstant` `!Send` while making the Rust compiler happy is much challenging.

The difficulty here is that the rust compiler is current not smart enough to do `Send` analysis (https://github.com/rust-lang/rust/issues/68112).

I think we can solve the problem first. After the Rust compiler becomes smarter, make `PerfStatisticsInstant` `!Send`.

**Comment by breeswish** [comment]
Considering that this involves some rust core change, maybe we can drop or separate the goal `Add !Send to PerfStatisticsInstant`? @sticnarf

**Comment by sticnarf** [comment]
> Considering that this involves some rust core change, maybe we can drop or separate the goal `Add !Send to PerfStatisticsInstant`? @sticnarf

Sounds a good idea.
