### ISSUE TITLE
UCP: JSON log format

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#7732]
## Description

Now TiDB supports outputing log in JSON format. TiKV can add support as well.

https://github.com/tikv/tikv/issues/1532

## Difficulty

- Easy

## Score

- 299

## Recommended Skills

- Rust

**Comment by weihanglo** [comment]
@breeswish , I am interesting in this issue but need to make sure i am on track.

First, we've got a [Unified Log Format](https://github.com/tikv/rfcs/blob/master/text/2018-12-19-unified-log-format.md) across several TiDB components in text format. Is there any specification descrbing how to handle JSON log format? 

Second, after testing nightly TiDB, I failed to log in JSON format no matter how was the config file set. I've set it as following but the output was never changed:

```toml
[log]
format = "json"
```

With my begineering-level golang knowledege, I investigated the logging functionalities which located at [util/logutil/log.go#L213-L222](https://github.com/pingcap/tidb/blob/a9dc72cf25589bc00260f1af4e5a17dac0f66474/util/logutil/log.go#L213-L222) and zaplog [zap_text_encoder.go](https://github.com/pingcap/log/blob/d28c14d/zap_text_encoder.go) and still found nothing related to JSON formatting. Although in zaplog part it may pass to zalog directly (haven't thoroughly traced), it seems that `logutil` always create a `textFormatter` without regarding `cfg.log.format`. If there is a way to log in JSON format, I would be happy to test it on my own!

The last is about implementation thoughts. If I read the source code correctly, our logging depends a lot on `slog` crate with a customized `TiKVFormat` drain implementing our own `fn log(...)`   to provide TiDB Log Format. Therefore, in order to achieve this feature, there are some tasks:

1. add a `format` field to `tikv::config::TiKvConfig`
2. implement JSON formatting logic to serialize timestamp, level, file:line, message, and fields. 

That's all I currently thought of. Hope I didn't missing any significant parts. Need helps and advice. Thanks!

**Comment by breeswish** [comment]
@weihanglo Thanks for the report. I'm forwarding this issue to the TiDB team to take a look at JSON issue. For the TiKV part:

> Is there any specification descrbing how to handle JSON log format?

Ideally we should follow TiDB's format. However since TiDB format doesn't work now, then.. there is no formal format now...🤣

> Therefore, in order to achieve this feature, there are some tasks

Yes, I think the steps are totally correct. You can go ahead. Remember to also change our config template in the `etc` directory.

**Comment by lysu** [comment]
@weihanglo emmm... you are right, current pingcap/log couldn't output as json(so pd or tools also need same problem), we will fix it at https://github.com/pingcap/log/pull/10
