### ISSUE TITLE
failpoints::test_register::test_merge not work

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#8244]
### What version of TiKV are you using?
Master

### Steps to reproduce
z cdc && cargo test --test tests --features failpoints,prost-codec -- failpoints::test_register::test_merge --exact --nocapture

### What did you expect?
failpoint code executes after `fail::cfg(commit_merge_fp, "pause").unwrap();` but indeed it not

**Comment by sticnarf** [comment]
### Bug

#### 1. Root Cause Analysis (RCA) (optional) 

We cannot run failpoint tests concurrently. Different failpoints may interfere with each other in concurrent tests.

#### 2. Symptom (optional)

No symptom. It's only a test failure.

#### 3. All Trigger Conditions (optional)



#### 4. Workaround (optional)

#### 5. Affected versions

Master

#### 6. Fixed versions

Master
