### ISSUE TITLE
cases::test_coprocessor::test_parse_request_failed_2 not work

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#8255]
### What version of TiKV are you using?
master

### Steps to reproduce
- add `println!("list {:?}", fail::list());` at `fail_point!("rockskv_async_snapshot",`
- `cargo test --package tests --test failpoints -- cases::test_coprocessor::test_parse_request_failed_2 --exact --nocapture`

### What did you expect?
fail::list prints failpoint configuration

**Comment by BusyJay** [comment]
Does it still exist on master?

**Comment by MyonKeminta** [comment]
You added the println statement to the `async_snapshot` function. However, the test means to return an error when parsing the request, which happens before `async_snapshot` function. So actually `async_snapshot` function should never be invoked, so the message you added is expected never to be printed. So as I understand it the test works well. If you comment out `fail::cfg("coprocessor_parse_request", "return()").unwrap();` and `assert!(resp.get_other_error().contains("unsupported tp"));`, the test will panic at failpoint `rockskv_async_snapshot` because it's configured so.
