### ISSUE TITLE
Reduce the number of read-proposal send to raft-store-thread

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/tikv#8724]
### Problem Description
![image](https://user-images.githubusercontent.com/16376959/93971094-f75f4780-fda1-11ea-898c-7233cf87bf2b.png)

We found that when TiKV call `raftkv.async_snapshot`,  there are a lot of read-proposal send to raft-store-thread, but only few of them execute as `read-index` and most of them execute as `local-read`. It means that most of request are still in a leader lease but they are still send to raft-store-thread. LocalReader may believe the lease of leader is expired mistakenly.

We need to investigate this problem and find how to make local reader judge lease more accurately.

**Comment by BusyJay** [comment]
May be related to #5388.

**Comment by gengliqi** [comment]
I think it's caused by L462 https://github.com/tikv/tikv/blob/bc61a573c6fab93dffc5fc8f9ab981f3d8a78b21/components/raftstore/src/store/worker/read.rs#L461-L476
For normal cases, if the lease is expired, the `self.delegates.get(&region_id).is_some()` will be true so this read request must be redirected to raftstore.

I think this behavior is not expected.
